### ISSUE TITLE
Add 'Album.Year' as a path format option

### ISSUE THREAD

**Issue by ibleedlemonade** [svbnet/Athame#104]
I've first used Athame with the [Deezer plugin](https://github.com/TripleFrequency/AthamePlugin.Deezer) which allowed me to automatically put the release year of an album in the folder name with the 'Album.Year' tag but when I tried to use the default Tidal plugin with the same folder name template it didn't add any year in my folder names and just left it blank.

My template is `{AlbumArtistOrArtist} - {Album.Title} ({Album.Year})`

Deezer:
> Link: http://www.deezer.com/us/album/39949511
> Folder: Kendrick Lamar - DAMN. (2017)

Tidal:
> Link: https://listen.tidal.com/album/72694579
> Folder: Kendrick Lamar - DAMN. () 

It'd be nice to have it work for the Tidal plugin as well so I don't have to manually input the release years in my folder names.

**Comment by Freetekno** [comment]
Hi. Use {Year} for folder name.

**Comment by ibleedlemonade** [comment]
Yep, {Year} works fine for both Deezer and Tidal, thank you.
I do think that {Year} should be added in the "Path format help" window in the general settings since I thought {Album.Year} was the only one that existed.

**Comment by svbnet** [comment]
Overlooked this. The plugin API is quite confusing regarding whether to use `Track.Year` (i.e. `{Year}`) or `Album.Year`, but it should be possible to keep on using `{Year}`.
