### ISSUE TITLE
Athame downloads the last track but gets stuck!

### ISSUE THREAD

**Issue by deexo** [svbnet/Athame#105]
OS: Windows 10
I have deleted the config file.
I am using version 0.4.6
Yes I can playback the track.

The last track of every album downloads and Athame is "finished" - but its stuck at the loading bar 
https://i.imgur.com/EMfwYNm.jpg

The only way to fix this is by restarting.

**Comment by kingofwap** [comment]
Facing same issue on the latest update

**Comment by deexo** [comment]
![image](https://user-images.githubusercontent.com/25941258/34081650-391d1b56-e348-11e7-9926-1fa53576c452.png)

This has now occurred, last song can be played on the tidal app but it saves as m4a-temp and cannot be played locally.

**Comment by deexo** [comment]
Also mentioning this is for Tidal services if it matters.

**Comment by svbnet** [comment]
I think this should be fixed in the upcoming minor release. However, the progress bar issue is quite difficult to work on at the moment.
