### ISSUE TITLE
Athame does not download album artwork

### ISSUE THREAD

**Issue by ibleedlemonade** [svbnet/Athame#106]
What is your OS version? - Windows 10
Have you deleted your config file? - Yes
Have you ensured you are using the latest version? - Athame 0.4.6
Can you play back the track or collection on the web? - Yes

I've tested with the Deezer and Tidal plugins. 
"Save Album Artwork" in the settings is set to "As cover.ext".

**Comment by deexo** [comment]
Can confirm the same issue.

**Comment by svbnet** [comment]
Whoops! This should only happen when the "Don't save album artwork when downloading a playlist" option is set but I forgot to add the check whether the item downloading was actually a playlist. Pushing a new release that also should fix #105.
