### ISSUE TITLE
Santa Claus Memes **Not Clickbait**

### ISSUE THREAD

**Issue by ThePlayingGoblin** [svbnet/Athame#108]
I would like to have Deezer Plugin A3 and A2 if anyone has them. I accidentally got rid of them and I don't really like A3.1.

**Comment by fabriccioguzman** [comment]
I think this is the
[Deezer.zip](https://github.com/svbnet/Athame/files/1585122/Deezer.zip)

**Comment by ThePlayingGoblin** [comment]
Pretty sure its A2 when comparing google cache with the latest updated file. Thank you though :)

**Comment by ThePlayingGoblin** [comment]
Just tested.  Appearently I still get the same issue when adding this link: http://www.deezer.com/us/album/53014082 both A2 and A3.1. If only DMCA hasn't taken it down, this could've been fixed :(

**Comment by Refelinux** [comment]
**fabriccioguzman** 
I recommend removing the plugin from here, because the athame page can be banned because of your comment.

**Comment by ThePlayingGoblin** [comment]
I think it should be reuploaded with a different file name and password protected with a pastebin link containing the password.

**Comment by ThePlayingGoblin** [comment]
@fabriccioguzman, you can delete the comment now. I have a little christmas treat for those who just found out about the essentials.

**Comment by shillshocked** [comment]
@ThePlayingGoblin Oh? :D
