### ISSUE TITLE
help, triplefrecuency athame plugin deezer deleted by github dmca

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#110]
Help, please someone could continue with this project with another project name and host it to mega or external links and in a description of the project that says that this download music from YouTube and it is safer that they do not eliminate it and only discover those that do not they give and want to try it and this is what new users discover Or that someone communicates with triplefrecuency to continue with this project in this way or the project mode of j0shi
![image](https://user-images.githubusercontent.com/27593140/34329746-08775d9e-e8da-11e7-8ffd-3d57dbbc20b4.png)

**Comment by ThePlayingGoblin** [comment]
I've contacted TripleFrequency already. The project has been discontinued and does not want any more trouble with the DMCA. Although I think it could've still been continued on a different platform than github.

**Comment by fabriccioguzman** [comment]
@svbnet @ThePlayingGoblin 
Help, please someone could continue with this project with another project name and host it to mega or external links and in a description of the project that says that this download music from YouTube and it is safer that they do not eliminate it and only discover those that do not they give and want to try it and this is what new users discover Or that someone communicates with triplefrecuency to continue with this project in this way or the project mode of j0shi

continue with the project athame plugin deezer

**Comment by fabriccioguzman** [comment]
@ibleedlemonade because dislike, deezer has more catalog than tidal, for you do this

**Comment by jonaaa20** [comment]
I'll dislike again, hey, calm down, there's a lot of alternatives out there, even that browser plugin still works, deezer premium enabler still works too, so, can you please stop? @TripleFrequency WILL NOT KEEP THE DEVELOPMENT DUE TO DMCA...

**Comment by fabriccioguzman** [comment]
@jonaaa20 wow wow I'm not disrespecting triplefrecuency and adema I communicate with fatkiwi by telegram and he shared the deezer plugin for athame and he said he will continue with the project but when I use the plugin in athame in the info says https: // github.com/jonaaa20/AthamePlugin.Deezer in the app athame
And by the way, do you have the source code? ? I asked you in telegram? if you told me you did not have it? so why do you publish this https://github.com/jonaaa20/AthamePlugin.Deezer and why do you appear in athame if fatkiwi is the one who will continue the project

please clarify it please

**Comment by fabriccioguzman** [comment]
@jonaaa20 I do not like using deezer download & deezer premium mod for greasymonkey in chrome because it does not insert tags and covers

**Comment by jonaaa20** [comment]
If you don't like it, well, I can't do nothing for you...

**Comment by FatKiwi** [comment]
It will be published soon. No need to discuss things in such detail everywhere. Thanks very much.

**Comment by fabriccioguzman** [comment]
@FatKiwi @jonaaa20 I do not understand you, because jonaaa20 appears in the info of your plugin, if fatkiwi is the editor of deezer plugin currently

**Comment by shillshocked** [comment]
Hopefully, we'll see higher quality album art. Deezer supports up to 1400x1400, and 300 DPI.

You can see a sample here:
https://e-cdns-images.dzcdn.net/images/cover/e6e520deb462978037bc0810a24cfb98/1400x1400-000000-100-0-0.jpg

Currently I'm getting 1200x1200 and I think it's with a URL like this:
https://e-cdns-images.dzcdn.net/images/cover/e6e520deb462978037bc0810a24cfb98/1200x1200-000000-80-0-0.jpg

HIgher quality can be obtained if you use the 100 instead of 80, and 1400x1400 instead of 1200x1200

**Comment by FatKiwi** [comment]
@shillshocked this is new. It's indeed 1400 pixels. Maximum I was able to fetch was 2000, but in rare cases. Quality 100 is useless, but is already added.

**Comment by shillshocked** [comment]
There is a quality difference between 80 and 100...it's noticeable and the size is different.

**Comment by FatKiwi** [comment]
I know that, and quality 100 is useless. You don't wanna have +6mb per file for cover. 94 is best, each step after you cannot notice quality difference and becomes too big.
