### ISSUE TITLE
For those who need essentials

### ISSUE THREAD

**Issue by ThePlayingGoblin** [svbnet/Athame#111]
The essentials are password protected in a .rar file, then zipped again in a .zip file as github doesn't support rar.
[ImportantEssentials.zip](https://github.com/svbnet/Athame/files/1586090/ImportantEssentials.zip)
The password can be obtained by going to the pastebin website and adding the code below.
sFkrU6gw

**Comment by shillshocked** [comment]
Password doesn't work for me. Checksum error.

**Comment by ibleedlemonade** [comment]
Worked fine on my end. Tried redownloading the .zip?

**Comment by redreadnut** [comment]
@shillshocked Try again )
worked for me

**Comment by shillshocked** [comment]
Just tried downloading again.

Z:\ImportantEssentials.rar: Checksum error in the encrypted file Z:\ImportantEssentials.rar. Corrupt file or wrong password.

**Comment by ThePlayingGoblin** [comment]
@shillshocked, sFkrU6gw is the code you paste after the forward slash at the pastebin website.

**Comment by shillshocked** [comment]
Pastebin?

Anyways, I tried that password and it said error.

**Comment by ibleedlemonade** [comment]
I don't like that question mark, @shillshocked. You sure you read the entire first post?

**Comment by shillshocked** [comment]
You do not refer to the pastebin website in the first post. Hence the question.

Look, the link is gimped. It obviously needs to be reuploaded. It will not extract, you can download and try for yourself.

**Comment by ibleedlemonade** [comment]
@shillshocked [This first post.](https://github.com/svbnet/Athame/issues/111#issue-284465282) The instructions are right there. Literally downloaded and opened it 48 seconds ago as of this comment.

**Comment by shillshocked** [comment]
Ah, OK I get it now. Skimmed over that bit. :)

**Comment by ThePlayingGoblin** [comment]
@shillshocked One is experimental (higher version) and one is more stable (lower version). The lower version is the recommended version, but the higher version is faster.

**Comment by andr3wy** [comment]
I have a suggestion: @svbnet you should give users the option to pause the download, and also, add on more downloads during the quene.

**Comment by itsmidnightyo** [comment]
i see what you did there. goes to show how we quickly jump to conclusions, lmao! thanks so much. :))

**Comment by svbnet** [comment]
Damn, had no idea that the plugin was taken down. Deezer seems to be the only website that actively goes after people who use the API, probably because it's very easy now to get good quality MP3s without paying for a subscription.

**Comment by ThePlayingGoblin** [comment]
What really sucks was the plugin @TripleFrequency made was so close to perfection. Just a few more updates and it would've been the most robust plugin the internet has to offer. Even right now it still performs really well.

**Comment by svbnet** [comment]
Also does anyone have a zip/folder of the latest commit? Email it to me at joe@svbnet.co

**Comment by shillshocked** [comment]
How recent was the latest?

**Comment by ThePlayingGoblin** [comment]
@svbnet you might have to contact @TripleFrequency

**Comment by fabriccioguzman** [comment]
@svbnet sorry joe, I have version 2.1, and contact me with triplefrecuency and do not plan to share the code because of dmca

**Comment by FatKiwi** [comment]
Here will be the issue tracker: https://github.com/jonaaa20/AthamePlugin.Deezer together with compiled .dll. It will be posted soon.

> Changelog:
> 1.4
> - Added image type & quality settings.
> - Added support for 2000x2000 artworks.
> - Fixed a bug that caused long filenames

**Comment by jonaaa20** [comment]
@svbnet Please close the issue.

**Comment by kleagon** [comment]
Will there be support for artist URL with this plugin?

**Comment by ThePlayingGoblin** [comment]
@jonaaa20 be careful. I don't want to see this plugin go as well.
