### ISSUE TITLE
Qobuz leecher maybe? Can somebody turn this into an athame plugin with flac?

### ISSUE THREAD

**Issue by FutureLeaker** [svbnet/Athame#121]
@TripleFrequency @J05HI @svbnet 

https://github.com/whiteisthenewblack/qobuz-get

**Comment by FutureLeaker** [comment]
Btw why can't I dl smloadr :(

**Comment by fabriccioguzman** [comment]
@FutureLeaker BY DMCA, reported by deezer a dmca for deleted

**Comment by J05HI** [comment]
@FutureLeaker 

Use the google webcache (link to Telegram groups is in there):
https://webcache.googleusercontent.com/search?q=cache:https://github.com/J05HI/SMLoadr

**Comment by fabriccioguzman** [comment]
@J05HI sorry by this, I write without thinking, I'm sorry

**Comment by fabriccioguzman** [comment]
@FutureLeaker links is down

**Comment by J05HI** [comment]
Yeah take a look at the news channel

**Comment by fabriccioguzman** [comment]
![image](https://user-images.githubusercontent.com/27593140/34628456-6cf20290-f232-11e7-855c-879d75a67f7a.png)

**Comment by Freetekno** [comment]
@svbnet, please close this issue.

**Comment by fabriccioguzman** [comment]
@svbnet, close this issue.
