### ISSUE TITLE
Capped at 48000hz

### ISSUE THREAD

**Issue by danorman7951** [svbnet/Athame#123]
Why doesn't Athame download at original Hz Just wondering,

**Comment by Hermit121** [comment]
It is downloading the correct files Tidal has.
CD Quality: 16Bit 44100hz
MQA can be: 24Bit 44100hz or 48000hz
To playback those files at the original sample rate you will need a MQA certified DAC or software. The Tidal Desktop App is capable to decode MQA files to a max of 96kHz (is referred as first unfold).

Athame itself does everything right and there is nothing on Athame site that could be done different to unlock MQA files

**Comment by FatKiwi** [comment]
Also you can use MediaInfo and check the files. MQA files have ORIGINALSAMPLERATE, which is the original Hz masters info before folding it to MQA.

**Comment by svbnet** [comment]
@Hermit121 is correct. MQA needs to be decoded by a specialised MQA algorithm/device. The "master" download option is only provided so that if someone manages to get an MQA player implementation working in the future they can be played back at full quality.

**Comment by Hermit121** [comment]
@svbnet Actually if you own a MQA Decoding DAC or Player it will show as MQA and decode it.
