### ISSUE TITLE
Only working in Hi-Fi account?

### ISSUE THREAD

**Issue by luigyy23** [svbnet/Athame#124]
I have a problem

![sin titulo](https://user-images.githubusercontent.com/35316350/34802237-43df008e-f64b-11e7-95f3-f53e3028bd4b.jpg)

**Comment by FatKiwi** [comment]
What do you mean? It's not working with free account.

**Comment by jonaaa20** [comment]
This only works with a premium account.

**Comment by luigyy23** [comment]
It does not work on Tidal premium accounts, I had to upgrade to Hi-Fi to make it work.
![tidal](https://user-images.githubusercontent.com/35316350/34858399-def634d2-f72e-11e7-8e9e-0a48ca3735f4.jpg)

**Comment by FatKiwi** [comment]
You can't download FLAC with Premium.

**Comment by svbnet** [comment]
You need to go into settings and set the quality setting for Tidal to "High".
