### ISSUE TITLE
deezer problem with downloading

### ISSUE THREAD

**Issue by tine123** [svbnet/Athame#126]
Hello
I have a problem downloading from deezer.
Let's say when I want to add a moving window appears
https://imgur.com/a/Ulb1Z
It lasts and lasts and does not add an album.
Im asking for help
thank you

**Comment by FatKiwi** [comment]
It's currently not working. And this is not the place to report issues for Deezer plugin.

**Comment by tine123** [comment]
thank you
where can I find more information or where can I report on this?

**Comment by FatKiwi** [comment]
More information here: https://github.com/jonaaa20/AthamePlugin.Deezer/issues/5
