### ISSUE TITLE
InvalidArgument Errors

### ISSUE THREAD

**Issue by hjtech** [svbnet/Athame#13]
These errors are sporadic, but usually happens with large collections. In order to continue the download it requires a restart of the app, which removes the pending tasks.

![screen shot 2017-04-20 at 11 55 19 am](https://cloud.githubusercontent.com/assets/9100014/25252393/cfaa20da-25ea-11e7-949f-0ae1350ae5fd.png)
![screen shot 2017-04-20 at 2 53 15 pm](https://cloud.githubusercontent.com/assets/9100014/25252392/cfa995e8-25ea-11e7-9433-6a48a2c295ee.png)

On a side note: will there be support for Master files? `https://support.tidal.com/hc/en-us/articles/115000397069-TIDAL-MASTERS`

**Comment by svbnet** [comment]
The main queue list is very buggy - all I can recommend at the moment is that you remove items after they're downloaded from the queue list. Also, I think masters use the same quality setting as "HiFi" but I don't have a premium Tidal subscription so I can't test it at the moment.
