### ISSUE TITLE
more tags for tidal and google play music plugin athame

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#131]
please tags for tidal and google play by ej: ISRC, LYRICS, Recorded date or year more extended, Genre, BPM  and others

**Comment by redreadnut** [comment]
guzman, where is my comment? and why you need all this useless sh..it?? such a ISRC and BPM

**Comment by svbnet** [comment]
These are things that some services can and can't provide, in the case of lyrics would require another service, and are also unsupported or not implemented in the tagging library I'm using.
