### ISSUE TITLE
Cant use the Athame zip

### ISSUE THREAD

**Issue by Zapps7** [svbnet/Athame#132]
I'm using Win7 and cant use the program from Athame zip, had to resost to using the program from Plugin zip. it has 2 issues:

1) I am unable to paste the URL, so I have to manually type each link.

2) I cant access the files normally through the windows explorer. the files are only visible if i access the files by right click on the downloaded file.

**Comment by Zapps7** [comment]
just found where the files are stored - C>VTRoot>

**Comment by FatKiwi** [comment]
Fix your windows.
1. Urls are working
2. Files are visible even for youi.

**Comment by Zapps7** [comment]
They are working using the program main zip zile, which is working even for my friend, But on my PC, when I try to open the program, it says plugins are missing.

**Comment by svbnet** [comment]
Have you downloaded the base plugins zip? That includes Google Play and Tidal. Also can you do Ctrl-V into the URL text box?
