### ISSUE TITLE
Tidal: File plays fine but can't be downloaded

### ISSUE THREAD

**Issue by FLiNT-13-7** [svbnet/Athame#134]
Q: What is your OS version?
A: Windows 10 Pro

Q: Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.
A: Yes (multiple times)

Q: Have you ensured you are using the latest version? 
A: Yes

Q: Can you play back the track or collection on the web?
A: Yes (at any chosen quality)

Album URL: https://listen.tidal.com/album/79687809
Track URL: https://tidal.com/track/79687810

When trying to download this file (using either URL), Athame shows me the following error report:

![clipboard 1](https://user-images.githubusercontent.com/36166008/35816973-658a8db0-0a9c-11e8-8684-5820a0048138.png)

Additional information:
- The issue occurs no matter what download quality is chosen in Athame settings.
- Friends with Tidal accounts from different regions were able to recreate the issue, so it doesn't seem to be region-specific.

**Comment by cdyax** [comment]
Same problem

**Comment by FLiNT-13-7** [comment]
Found another release that is affected:
https://listen.tidal.com/album/77447804

**Comment by fabriccioguzman** [comment]
Apparently this is a problem in the tags or info that the release date is null so athame tidal gives this problem because it does not skip this error and it is what the dev must do to skip this error

**Comment by FatKiwi** [comment]
Can confirm. This bug exists.

**Comment by svbnet** [comment]
Fixed - see https://github.com/svbnet/AthamePlugin.Tidal/releases/tag/2.3.1

**Comment by cdyax** [comment]
Thank, gracias

 

De: Joe [mailto:notifications@github.com] 
Enviado el: jueves, 8 de febrero de 2018 11:32
Para: svbnet/Athame <Athame@noreply.github.com>
CC: cdyax <cdya@cdya.com>; Comment <comment@noreply.github.com>
Asunto: Re: [svbnet/Athame] Tidal: File plays fine but can't be downloaded (#134)

 

Fixed - see https://github.com/svbnet/AthamePlugin.Tidal/releases/tag/2.3.1
