### ISSUE TITLE
Write directory on our own

### ISSUE THREAD

**Issue by ankit-nigam** [svbnet/Athame#135]
Hello, i too have a request regarding directory shortcuts, will it be possible to write directory on our own instead of selecting from Browse button everytime? So if i download an album it's saved in my main E:\Music\Music320 folder but sometimes i only download singles so i save it E:\Music\Music320\Singles folder, so it's just easy to write on our own sometimes it's just adding a word or deleting a word to the directory. Thanks :)

**Comment by svbnet** [comment]
In the Settings window, you can have Athame ask you every time where you'd like something downloaded:

![image](https://user-images.githubusercontent.com/3015323/42158737-746f3f8e-7e45-11e8-97bd-97f819dc1180.png)
