### ISSUE TITLE
Qobuz to be released in the USA?

### ISSUE THREAD

**Issue by ThePlayingGoblin** [svbnet/Athame#137]
So I randomly visited qobuz's website to search an album when I got this prompt.
![qobuz](https://user-images.githubusercontent.com/32787189/36273554-a9be6a70-1239-11e8-9aa2-e4de0c6259ba.png)
Does this mean a qobuz plugin will finally be on its way? Will a subscription be required? Will it be like deezer with no subscription required?

**Comment by Kawashi666** [comment]
First, this isn't a issue

Second, you can download from them using URL snooper + IDM, no tags included

Third, their catalog sucks.

Fourth, Tidal still have a better catalog than qobuz.

**Comment by shillshocked** [comment]
If it's launching in the US, I imagine their catalog will improve vastly.

**Comment by FatKiwi** [comment]
Athame doesn't support Qobuz and it probably won't soon.
