### ISSUE TITLE
Error when downloading some albums TIDAL

### ISSUE THREAD

**Issue by bukakow** [svbnet/Athame#138]
What is your OS version?
**Windows 10 64-bit**

Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.
**Yes**

Have you ensured you are using the latest version?
**Yes**

Can you play back the track or collection on the web?
**Yes**

Some tracks on some albums can not be downloaded from TIDAL.
For Example, try this: https://listen.tidal.com/album/4683997

![obraz](https://user-images.githubusercontent.com/36563739/36340295-35963b4e-13da-11e8-8ce4-700d452af9dd.png)

**Comment by kmafitz1** [comment]
Same problem here , buts works ok with deezer

**Comment by Ant4rez** [comment]
I have the same issue i can't download this https://listen.tidal.com/album/31415778

**Comment by TripleFrequency** [comment]
On the *original* album provided, it likely has to do with path length, which is limited to 260 characters on Windows. There seems to anywhere from three to nine or more featuring artists on each song, which easily surpasses that limit.

@svbnet Could likely just slightly change the name joiner or name helper in the Tidal plugin to use "Various Artists" as a replacement for the featuring list or artist name if, for example, you have more than 5 featuring artists, and the joined name is over 60 characters.

As for your issue, @Ant4rez, I would create a separate issue, it seems unrelated.

**Comment by Ant4rez** [comment]
I delete the %appdata% and it works:D, thanks.

**Comment by FLiNT-13-7** [comment]
I can confirm that path length is the culprit here (at least in Bukakow's case). Change it from the original
`{AlbumArtistOrArtist} - {Album.Title}/{TrackNumber} {Title}`

to something more basic like this
`{TrackNumber} {Title}`

and you are good to go.

**Comment by FLiNT-13-7** [comment]
@Ant4rez The album in the link you provided works fine for me. Are you sure that the link matches your account's region?

**Comment by MusicBits** [comment]
I have same problem. All red crosses. Worked fine i 0.4.6.1. :-)

**Comment by svbnet** [comment]
Unfortunately it's difficult to fix this issue - since Athame can't really shorten paths, the only solution is the one above.
