### ISSUE TITLE
Athame always download only 160 kbps MP3 from google play

### ISSUE THREAD

**Issue by Degitalord** [svbnet/Athame#14]
I want the MP3 320 but Athame downloads only MP3 160 irrespective of the settings. I already selected play music to stream in high quality and setted 320 mp3 in athame settings  but still downloading 160 pls fix the issue. I'm using 0.4 version

**Comment by svbnet** [comment]
I cannot seem to replicate this - my guess is that the Play Music API is returning a lower-quality track for some reason.
