### ISSUE TITLE
ALERT, THE SAFETY HOLE CORRECTED ON THE WEB PLAYER

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#140]
(confirmed) the dev of tidal and wimp learned of the security hole that the web player had because in the last days they have made changes in the web and they repaired it
https://api.tidal.com/v1/tracks/75413012/streamUrl?soundQuality=LOSSLESS&urlusagemode=STREAM&assetpresentation=FULL&&sessionid=a7090099-125b-4c3e-be8c-cd6539520e1d&countryCode=DE

**Comment by Kawashi666** [comment]
There's no need to open a issue about this...

**Comment by FatKiwi** [comment]
Bullshit. Everything is working as it should.
