### ISSUE TITLE
False positive? Trojan:Win32/Critet.BS

### ISSUE THREAD

**Issue by aardigevent** [svbnet/Athame#141]
Windows Defender reports Athame 0.4.7 as containing a trojan: Trojan:Win32/Critet.BS. Athame 0.4.6.1 and earlier releases do not have this problem.

**Comment by 6uru** [comment]
I have the same issue as above.

![athame-windowserror png](https://user-images.githubusercontent.com/11576393/37564407-62527ca4-2abb-11e8-9f92-c041039ee266.png)
![athame-windowsdefender png](https://user-images.githubusercontent.com/11576393/37564408-68675ab0-2abb-11e8-8b26-63f31e688a70.png)

**Comment by redreadnut** [comment]
amazing

**Comment by svbnet** [comment]
Scans fine on Windows 7.

**Comment by aardigevent** [comment]
Uhm, latest Windows 10 Defender definitions still marks Athame as containing a trojan.

**Comment by jonaaa20** [comment]
Just add to your exclusions dude. Windows Defender sucks btw.
