### ISSUE TITLE
Bulk pasting

### ISSUE THREAD

**Issue by idliketoknow** [svbnet/Athame#143]
Great little app.

Could we get bulk pasting as an option?

When downloading in large quantities it can be tiresome to keep pasting individual URLs in.

**Comment by acm4dino** [comment]
2nd that!
They're working on getting "album browsing" from artist page working.
I'd settle for a good old clipboard monitor with toggle.

**Comment by d2dyno** [comment]
Something like links separated by lines or reading from a file would be really useful.

**Comment by svbnet** [comment]
Added :)
