### ISSUE TITLE
401 errors occurring when downloading album

### ISSUE THREAD

**Issue by w-biggs** [svbnet/Athame#145]
**What is your OS version?** Windows 10 Home (1709, build 16299.309)
**Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.** Yes.
**Have you ensured you are using the latest version?** Yes.
**Can you play back the track or collection on the web?** Yep. https://listen.tidal.com/album/83759170

Not much more to add. I've attached a screenshot of the error. I've tried signing out and signing in again to no avail.

![image](https://user-images.githubusercontent.com/3406010/38009052-2d9b30f2-3220-11e8-8145-d213b2d46634.png)

It shouldn't be a subscription issue either:

![image](https://user-images.githubusercontent.com/3406010/38009105-746e4492-3220-11e8-975f-dbc67668b72f.png)

**Comment by Hermit121** [comment]
Do you have athame setup as FLAC ? with tidal premium you can only do aac/mp3

**Comment by w-biggs** [comment]
Wow, I'm dumb. lol. That was my issue. Thanks.
