### ISSUE TITLE
Can't download from google music, "The URL does not point to a valid track, album, artist or playlist"

### ISSUE THREAD

**Issue by Deanosim1** [svbnet/Athame#148]
So either I'm an idiot and missed something or this doesn't work anymore, I click share on a track, album or playlist and paste the URL into Athame and it just spits out "The URL does not point to a valid track, album, artist or playlist"

**Comment by FatKiwi** [comment]
For Google Music there are 2 types of links. One are store links with price next to each track, the other one is streaming link (this should work and requires subscription to download). Are you sure you're copying the proper url?

**Comment by svbnet** [comment]
Should be fixed https://github.com/svbnet/AthamePlugin.GooglePlayMusic/releases/tag/2.3

**Comment by Sheepdisease** [comment]
I installed the updated plugin which meant that Athame recognised the links. However, if I try to download anything it comes back with an error '"Error occurred while downloading" on all tracks. This happens every time no matter how long the list of songs is.
