### ISSUE TITLE
Tidal Plugin Master Samplerate

### ISSUE THREAD

**Issue by LetsPhoenixPlay** [svbnet/Athame#149]
!!! PLEASE READ THE README BEFORE FILING AN ISSUE OR REQUEST !!!
!!! ISSUES THAT HAVE ALREADY BEEN ANSWERED OR ADDRESSED WILL BE CLOSED !!!

If you've found a bug, please answer these questions:
What is your OS version? Windows 10 1709 Build 16299.371
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file. No
Have you ensured you are using the latest version? Yes
Can you play back the track or collection on the web? Yes

Tidal Master releases do not download with their original samplerate.

**Comment by Hermit121** [comment]
Tidal masters are MQA files, they are supposed to be either 24/44.1 or 24/48.

**Comment by SantoshStar** [comment]
what does that mean!?is the quality fake , low or good!?

**Comment by jonaaa20** [comment]
Some are fake, others not.

**Comment by Hermit121** [comment]
NO! They are not fake or not. The way MQA works is that it needs a decoder. If you dont have a compatible device (DAC or Player) that can do the decoding, they files will be of lower quality than normal CD Quality. If you dont know what you are talking about dont just make things up @jonaaa20

**Comment by SantoshStar** [comment]
I know what I am talking about just because I saw that some songs are up-sampled :) so some are up-sampled , most of them are true FLAC

**Comment by jonaaa20** [comment]
@Hermit121 instead of being a miserable bitch, let me explain just a thing, **THERE ARE FAKE MQA RELEASES ON TIDAL, EVEN ON STORES**, this applies to MP3 and FLAC too

> If you dont know what you are talking about dont just make things up

Friend, enough. MQA is just marketing, better use google and you'll see.

**Comment by Hermit121** [comment]
@jonaaa20 @SantoshStar, no track is upsampled (atleast MQA tracks). And there are no "FAKE MQA". MQA isnt just marketing, but you will not get the full sampling rate when playing on a non compatible device. I am by no means a support of MQA but what you are saying is just wrong.
