### ISSUE TITLE
the url provided may be invalid or unsupported

### ISSUE THREAD

**Issue by chrisdavery** [svbnet/Athame#150]
My OS is Win 8.1 ,athame is working before but now it has a problem like this ,pls provide me a solution for this problem. thank you
![image](https://user-images.githubusercontent.com/32586764/39680974-0c78d25c-51d9-11e8-98c8-83c854f2a083.png)

**Comment by feria35** [comment]
Just "Sign Out" ... and then "Sign In" again !

**Comment by chrisdavery** [comment]
![image](https://user-images.githubusercontent.com/32586764/40093847-90e6b896-58f6-11e8-8531-f3167589fd7a.png)
still not working my friend. im using 0.4.7 athame version

**Comment by redreadnut** [comment]
maybe this is the problem? - 

![40093847-90e6b896-58f6-11e8-8531-f3167589fd7a](https://user-images.githubusercontent.com/29500203/40132488-99ebe70a-5945-11e8-9857-1e98729641f7.jpg)

Use acc with subscription, it's not deezer and you need premium acc to download from tidal

**Comment by chrisdavery** [comment]
okay now i understand dude,the account subscription has expired . anyways,
how to download in deezer?

**Comment by mauriva** [comment]
Hi! Similar issue here.
I'm on Athame 4.7.0 on Windows 10 Pro 64 bit and I own an active premium account.
Athame worked for me for months, but yesterday first got the URL error. After Sign Out and Sign In the error was gone, but still I can not download anything:
![tidal](https://user-images.githubusercontent.com/39453887/40276731-0c42f806-5c12-11e8-8090-93bba7025d81.png)

**Comment by svbnet** [comment]
Log file?

**Comment by 615283** [comment]
I'm getting the same issue on some albums.

**Comment by svbnet** [comment]
@mauriva Unfortunately not - you'll need to use a VPN.

Please install the latest version of the Tidal plugin - https://github.com/svbnet/AthamePlugin.Tidal/releases/tag/2.3.1

**Comment by mauriva** [comment]
I think that VPN can not avoid the problem.
I use the last version of Tidal plugin.
I live in Italy, but I use an account that is not an italian one (it was registered in another country, but I don't wich one): I can not download the "italian" album also if I live in Italy, so I think that the block is not on the IP address, but on the account.
My question is: there is no way to avoid this block on the account? I don't think so, but asking...

**Comment by k3npachi** [comment]
i have the same error
