### ISSUE TITLE
"An error occurred while downloading this track" (Google Play Music)

### ISSUE THREAD

**Issue by athata** [svbnet/Athame#153]
What is your OS version?
**Windows 10 64 bits**
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file.
**Yes**
Have you ensured you are using the latest version?
**Yes**
Can you play back the track or collection on the web?
**Yes**, I even tried with another Google Play Music account and I encountered the same error

https://imgur.com/a/cHTeO7G

**Comment by AlexHaber** [comment]
# #151

**Comment by AlexHaber** [comment]
Same as #151

**Comment by nrafaelos** [comment]
Works fine ,until two weeks ago . For any album I want to download I get the message :An error occurred while downloading this track!

**Comment by jonaaa20** [comment]
Same as #151

**Comment by athata** [comment]
Thanks @AlexHaber
