### ISSUE TITLE
Tracks available in the desktop app but not in athame

### ISSUE THREAD

**Issue by mauriva** [svbnet/Athame#155]
Here is a link for an album that I can listen normally in the Tidal desktop app:
[Lin to album](https://tidal.com/album/84446028)
I can import the album in Athame (0.4.7.0) but not all tracks are available to download.
Obviously the account is the same both in the app and in Athame.
Here is a screenshot:
![stato](https://user-images.githubusercontent.com/39453887/41404273-0eba3694-6fc7-11e8-8145-036b48e8f2f8.png)

**Comment by SuPerCracKMaN** [comment]
if this has happened to me before, but it seems that joe ignored my problem and I do not repair it because of fatkiwi and the others, so I was forced to download it myself using the api API of the web player to be able to request and generate a download link in flac
reference to:

**Comment by SuPerCracKMaN** [comment]
#85 #86

**Comment by redreadnut** [comment]
@PanaDerux  Guzman, is that you? Stop changing nicknames so often. And thanks for mentioning me firstly in those topics where I didn't write anything.

**Comment by PanaDerux** [comment]
@redreadnut if I'm Fabriccio and I'm talking about you, like a long time ago you did not like my comment about a problem that I still have about the tidal plugin that when downloading a song that has a very long name it gives me a download error and the dev does not solved and I think it's the same what happens to @mauriva

**Comment by mauriva** [comment]
I don't know if the problem reported in my first post is about long name or not.
I add this information.
Some weeks ago the same album linked in the first post had the latest songs not available even in the Tidal desktop app. Then the app was updated and the songs became playable. Nothing has changed in Athame.

**Comment by svbnet** [comment]
If you've noticed, I've stopped committing and releasing new versions as frequently as I would like to, as I'm now working full time. This was a project started when I was unemployed, when I had much more free time available. Even though I do read through all of the issues and comments posted here, and I do plan to fix and implement any bugs and features posted, I simply cannot spend all of my time on this project. Athame certainly isn't dead, and I have big things planned for it, but software development takes time and energy that I have now much less of.

That being said, I still appreciate everyone who uses Athame, donated, or has submitted an issue. Without you guys, I would have abandoned this project ages ago.

**Comment by mauriva** [comment]
Thank you Joe for your work on Athame!
Don't worry about the delay in releases: I know what it means to have a job that leaves little room for your passions!

**Comment by svbnet** [comment]
Thanks for understanding. Unfortunately it seems that album is region locked, so I can't download it.
