### ISSUE TITLE
Error "retrieve information"

### ISSUE THREAD

**Issue by k3npachi** [svbnet/Athame#158]
Hi, first of all thanks for this fabulous software 

but lately I've had a problem, no links are working. 

I attach a capture it will be easier : https://i.imgur.com/aPI4Slw.png

Thanks again

**Comment by svbnet** [comment]
Make sure the account you're signed in to has an active subscription.

**Comment by k3npachi** [comment]
My fault, the subscription ended on the 11th

Thanks
