### ISSUE TITLE
Release 0.4.1 

### ISSUE THREAD

**Issue by alfablac** [svbnet/Athame#16]
Doesn't open.
Windows 10

**Comment by tocy777** [comment]
It does.
Windows 10
Try restarting your machine, I experienced something similar when I was running 0.4 I couldn't start up 0.3.2 but after a restart all was well.

**Comment by alfablac** [comment]
Not working after a restart. Don't know what it can be. It just crashes, don't even open.
Previous versions 0.3.2 and 0.4 are still working.

**Comment by svbnet** [comment]
Try deleting your config file. copy and paste this into the address bar: `%appdata%\Athame` then delete the settings.json file.

**Comment by alfablac** [comment]
First thing I tried. Still trying to find the bug. Compiled the source and it didn't work too.
Tried on two other Windows 10 systems and the same thing happens. It don't even open.
I'll continue to use 0.4 while I try to find a way to open it. Thanks for the work though!

**Comment by svbnet** [comment]
Hmm. I will try on my Windows 10 VM but I can't think off the top of my head what the issue would be.

**Comment by svbnet** [comment]
Seems to work fine on my VM, which is Windows 10 version 1607 build 14393.0, 64-bit. However, that has 4.6.2 which is what Athame is built against, so that is most likely the issue.

**Comment by alfablac** [comment]
According to the new log version:
[Fatal] AppDomain: Unhandled exception
NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at Athame.Plugin.PluginManager.<>c.<LoadAll>b__19_0(String dllPath)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at Athame.Plugin.PluginManager.LoadAll()
   at Athame.UI.MainForm..ctor()
   at Athame.Program.Main()

**Comment by alfablac** [comment]
No idea why Windows are doing this, but checking the "Unlock" box (mouse right-click > Properties) on the .exe and all .dll files fixes the problem. You can close the issue!

**Comment by svbnet** [comment]
Wow that's great. I'll see if I can try and handle this for the next version.
