### ISSUE TITLE
Athame not working on tidal and google play music

### ISSUE THREAD

**Issue by brynathemina** [svbnet/Athame#170]
If you've found a bug, please fill this out:

**What is your OS version? (e.g. Windows 7, 8, 10)**
Windows 10
[log20180825.log](https://github.com/svbnet/Athame/files/2320805/log20180825.log)

**What is the URL you're trying to download?**

**Have you made sure you have an active subscription for the service you're signed into?**

**Have you ensured you are using the latest version? ([click here to to go the releases page](https://github.com/svbnet/Athame/releases))**

**Can you play back the track or collection on the web, using the same account?**

**If possible, post a log file.**
*To do this, click the "Menu" button, then "About", then the "Support" tab, then "Open user data directory". In the window that opens, double-click the "Logs" folder, then drag the latest log file into this text editor (the file name will be "log", then today's date in year-month-day format). No personally identifiable information is stored in log files.*

**If Athame doesn't look right, please post a screenshot if possible.**

**Comment by FatKiwi** [comment]
#151 and Tidal is fine, your log and info is useless.
Close this.

**Comment by jonaaa20** [comment]
"Athame **not working on tidal**  and Google Play Music"

Why don't you read it? He was talking about athame, not the tidal itself friend, instead of being a rude bitch, learn to read.

Anyway, calm down, athame is working fine on tidal on my side.

**Comment by brynathemina** [comment]
+Fatkiwi ooohhh!!! lol oink oink! i have a lot of cunts in my life all i do is fuck them and throw them but you asshole is fucking stupid and brain dead. don't give lessons to your father son shoooo! find a job. ooohh!! anger anger hahaha lol
 i would have make you a  bitch if you stop behaving like a rat shit. not everyone is a programmer so understanding a log is not my thing. i upload this for author not for useless ratshit like you. if you mean anything for developer than learn to tag otherwise shut you ratface and do belladona on bamboo,
i am not a useless cause i don't talk shit to others can't say same thing about you ratshit. your life look like spam who is so useless and retarded he like to poke his nose on other people business. 
have a nice day bitch!

**Comment by ExtendLord** [comment]
lololololololol
@brynathemina Its funny the way you are mad, Mr. angry/spammer.

**Comment by brynathemina** [comment]
@ExtendLord what funny is you writing lololololololol like 5yo kid. now stop spamming my thread you joker

**Comment by jonaaa20** [comment]
Okay, @brynathemina, that's enough.

Its really funny to see you mad, you're probably a kid anyway.

**Comment by FatKiwi** [comment]
@brynathemina Bye Felisha!

**Comment by brynathemina** [comment]
@FatKiwi Jokes on you old stinky nagger. hahaha bye bye don't forget to put some lipstick on your double jolie lips so they stick together and stop oinking at anyone.

**Comment by brynathemina** [comment]
@jonaaa20  I AIN'T KID GAL!

**Comment by ExtendLord** [comment]
@brynathemina You mad kid?, just tell me what you're mad for.
