### ISSUE TITLE
TIDAL download error

### ISSUE THREAD

**Issue by WegoW** [svbnet/Athame#18]
On a few ablums i'm getting a CorruptFileException during download (s. screenshot). One of these albums is for example https://listen.tidal.com/album/17186342 . Any chance to fix this? This happens in 0.4 and 0.4.1.

![athame error](https://cloud.githubusercontent.com/assets/5252110/25744217/e8c24ab6-3198-11e7-965b-999e39733aae.JPG)

**Comment by svbnet** [comment]
Unfortunately, it seems like the AAC file header is corrupted, as Mp3tag, Windows Explorer and VLC fail to write a tag. You will most likely have to re-encode the file then manually add the tags. If this becomes a larger issue I might add a facility to do this automatically but it seems like most files are encoded correctly.
