### ISSUE TITLE
MQA Master Downloads

### ISSUE THREAD

**Issue by Hemps37** [svbnet/Athame#19]
What are the chances of being able to retrieve MQA Mastered files?

**Comment by svbnet** [comment]
I'm pretty sure the Lossless download setting will also download master quality files.

**Comment by Hemps37** [comment]
Thought so too but tested it by downloading 2 songs 1 MQA and the other HiFi and both come in at the same file size and also according to Spek are identical.
I believe only the Desktop app can play MQA at the moment and not mobile.

**Comment by hjtech** [comment]
It seems like only the desktop app can play those files.

**Comment by Hemps37** [comment]
Using desktop app and running fiddlerscript you can get URL and add to internet download manager which downloads the MQ file but it's still encrypted.

**Comment by tocy777** [comment]
Supposedly Chrome can play those as well and they are probably 24bit FLAC files.

**Comment by Hemps37** [comment]
Found this reference

// OpenTidl.Enums.SoundQuality
public const SoundQuality LOSSLESS_HD = 3;

Base Type
High
Lossless
Lossless_hd
Low

**Comment by smiba** [comment]
I've tried getting MQA to work before but I was unable to. Not sure if it's the OpenTidl code not having full support for this or Athame requiring a few changes before it works.

Changing it to lossless_hd does not work, even if tried to hard force it by changing some code

**Comment by svbnet** [comment]
I think LOSSLESS_HD is a deprecated constant - the only valid ones are `LOW`, `HIGH`, and `LOSSLESS`. I'm assuming that on a desktop session it will provide the master version at `LOSSLESS`, but that will most likely be an encrypted file, since the OpenTidl library works on a mobile session which can provide unencrypted files. I also do not have a lossless subscription since I can't afford it at the moment.

**Comment by Hemps37** [comment]
I downloaded a Hifi song on Android mobile app, switched to offline mode, connected it to pc and browsed to folder where the file is stored.
The file there and the file I can obtain via idm have identical names. (11c899aa544a7530e214ec3f332b7e0b_39.flac)
I replaced the Hifi file 32Mb with the MQA version 63Mb I got from IDM (encrypted)
Go back in to Tidal app and start playing the song, it plays , copy the song off the Android device onto Desktop and viola, I have the MQA version that just needs metadata.
The song has to play first within Tidal app , if you just copy it off the file before the play begins I'm guessing it's still encrypted.

**Comment by svbnet** [comment]
Very interesting. I'll try and look into that.

**Comment by Sonikko** [comment]
@Hemps37 Can you help me using Fiddlerscript? I'd like to give this a try!

**Comment by Hemps37** [comment]
Fiddlerscript used to work, now it only retrieves partial files, your best bet would be Wimp and download via IDM.

**Comment by Sonikko** [comment]
Wimp does not offer MQA tho, at least not on the web page, like Tidal. I don't think I can use the desktop app with IDM.

**Comment by Hemps37** [comment]
My mistake.

I opened Fiddlerscript, opened Tidal desktop app, played MQA song and saw link in fiddlerscript, added it to idm and downloaded it but it wouldn't play.
You have to install app on android, download the same song but hifi version then go offline.
Attach droid to pc and browse to where the file is, then replace that file with the same file you downloaded MQA quality, then open Tidal droid app.
Play song , whilst it plays copy the file back to pc and its un-ecrypted.

Phew!

**Comment by Sonikko** [comment]
@Hemps37  I managed to get the MQA song with IDM, but on Android it's not showing up with the same filename at all. Am I in the right folder, com.aspiro.tidal/offline/files?

**Comment by Hemps37** [comment]
Thats right place, strange.

I'll try it again later.

**Comment by Sonikko** [comment]
I get extensionless files with different names, not flac files. I'm using a Samsung Galaxy S Advance.
Thanks a lot for your help, I appreciate it!

**Comment by Hemps37** [comment]
MQA downloads are coming soon :)

**Comment by svbnet** [comment]
Currently working on master downloads. Should be available soon.
