### ISSUE TITLE
FLAC stream not found at starting position

### ISSUE THREAD

**Issue by Mrtenz** [svbnet/Athame#21]
I'm trying to download 3000 Days by The Pineapple Thief. I can play the song using the web client. I get the following error:

![Error](https://i.mrten.nl/lk2jgKCv4253.png)

The flac did download and I can play it without issues, but is not tagged. It seems to happen with all songs in the album.

**Comment by smiba** [comment]
Are you sure the file is a flac? If it's less then 12MB it's most likely actually an MP3

I know this was an issue in older versions of Athame but I heard it has been fixed. I haven't tested it myself

**Comment by Mrtenz** [comment]
Looks like it's not actaully a flac. Playing it with foobar2000 didn't work, after chaning the file extension to .mp3 it did.

**Comment by svbnet** [comment]
Yeah this should've been fixed. What's the version you're using?

**Comment by Mrtenz** [comment]
I was using 0.3.2 before. Using 0.4.2 won't show the message anymore and download the files as m4a, but still no tags.

**Comment by svbnet** [comment]
So no tags on FLAC files? That's very strange, since it should automatically be able to tag both FLAC and M4A. Would you be able to post logs? You can find the latest one by entering `%AppData%\Athame` into the file explorer address bar and pressing enter.

**Comment by Mrtenz** [comment]
Here is my log file: https://hastebin.com/mokefevika.pas

**Comment by svbnet** [comment]
Looks like it's related to Issue #18, where for some reason the headers present on Tidal's AAC files are corrupt but the audio content is not affected. Something like https://sound.stackexchange.com/a/37677 may work, since you'll also likely run into issues trying to tag them with a 3rd-party program.
