### ISSUE TITLE
Can we see a Deezer download option?

### ISSUE THREAD

**Issue by shillshocked** [svbnet/Athame#23]
I'm particularly interested in Deezer Elite, if that is possible, which I think it should be with some reverse engineering Sonos hardware...maybe an emulator?

**Comment by fabriccioguzman** [comment]
I also agree to incorporate deezer elite in this project, but sorry this project is in beta phase so you have to wait, the developer decides, since in his project says that he does not have many hours to athame by What he asks to help him contribute to solving problems

Will have to wait

**Comment by svbnet** [comment]
Deezer plugin is also in development.
