### ISSUE TITLE
error occurred while downloading

### ISSUE THREAD

**Issue by zakatov** [svbnet/Athame#24]
Most likely, the problem is that the album does not have a cover.

https://listen.tidal.com/album/69675449
https://listen.tidal.com/album/73467806
https://listen.tidal.com/album/73850371

Windows 10
athame-0.4.3

![error](https://cloud.githubusercontent.com/assets/19205539/26024795/fb603a76-37e1-11e7-989f-5fe95ea18fcd.png)

**Comment by svbnet** [comment]
For some reason the Tidal image server is returning a 403 Forbidden when retrieving the album art. Should be fixed in the next release.
