### ISSUE TITLE
Can't Download files that don't have album art.

### ISSUE THREAD

**Issue by stayxnegative** [svbnet/Athame#26]
Every time an album doesn't have album art in Tidal, it just gives me an error when I try to download said albums. 
![untitled-1](https://user-images.githubusercontent.com/29215335/26963448-996696ce-4cba-11e7-8d07-54ae10a778df.jpg)

**Comment by kmafitz1** [comment]
I noticed that https://listen.tidal.com/album/72072904

**Comment by svbnet** [comment]
Are you using the latest version?

**Comment by fabriccioguzman** [comment]
To me also is happening is in the last version 0.4.3, you have to program this program to download the flac or m4a music first and then the tags or info and cover

**Comment by stayxnegative** [comment]
I am using version 0.4.3, I don't know how to use any program for the source code. I just use the executable with the plugins.

**Comment by svbnet** [comment]
Should be fixed in the next release. The issue was when the "Save as file" album artwork setting was enabled, the track tagger would attempt to write the album artwork to file even if there was none available, causing the error.

**Comment by stayxnegative** [comment]
Thanks! I temporarily found a work around by using internet download manager and the http://play.wimpmusic.com to capture the unencrypted flac stream. So I was able to get the files that didn't have album art.
