### ISSUE TITLE
Track numbers

### ISSUE THREAD

**Issue by redreadnut** [svbnet/Athame#27]
hey! can you change a bit tracks numbering? like this 01. Song name, 02. Song name, 03. Song name....
or this will be also good 01 - Song name, 02 - Song name, 03 - Song name.

**Comment by smiba** [comment]
You can change this in the settings :)

**Comment by redreadnut** [comment]
wow, really!? I thought that it can't be modified to my needs. Anyway I still don't understand how to do it on this manner 01. Song name. Currently I have this 1 Song name. So how to add zero and a dot to this? can you throw me setting example for this?

**Comment by tocy777** [comment]
Yeah, how can that be achieved?

**Comment by kmafitz1** [comment]
Thsi is format for Mp3tag dont know if its same for Athame $num(%track%,2)

**Comment by redreadnut** [comment]
I think this format doesn't suits Athame. We should operate inside this settings by default - {AlbumArtistOrArtist} - {Album.Title}/{TrackNumber} {Title}
To get this 01. Song name
We have to change default something like this - {AlbumArtistOrArtist} - {Album.Title}/0{TrackNumber}. {Title}
It should work, BUT when it comes to 10 and more it will also add a zero before and we'll get this 010. Song name, 011. Song name and so on, thats not good :)

**Comment by svbnet** [comment]
Can implement this, hopefully in the next release.
