### ISSUE TITLE
It would be nice to create a plugin for spotify and others

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#29]
It would be nice to create a plugin for spotify (m4a), netease or 163.com (FLAC,MP4,MP3), qq music (FLAC,APE,MP3,MP4), kugou music(FLAC,MP3,MP4), kuwo music(MP3,MP4), Tidal Videos (TS), Crunchyroll (TS) in the future, Please

**Comment by alfablac** [comment]
Totally in favor of Spotify and Cruchyroll. The rest would be pretty hard to maintain IMO since there's no subscription options.

**Comment by redreadnut** [comment]
Is it really possible to download from spotify? Want to see Joe's comment about this. Actually would be great to see this option but it will be hard to reach :)

**Comment by alfablac** [comment]
It's probably possible, but I think Spotify files are encoded on ogg vorbis, a not so popular codec.

**Comment by redreadnut** [comment]
Don't forget that these ogg vorvis files are encrypted also.

**Comment by tocy777** [comment]
Spotify is in ogg, encoded and also in 20 pieces per files at best. What would we gain from this, I mean what music does Spotify have that Google Music and TIDAL doesn't?

**Comment by svbnet** [comment]
Spotify uses a proprietary transmission protocol for its desktop and mobile clients (the libreSpot project on here I think is a Rust implementation of that), but a websocket and Flash-based implementation for the web client. I have been investigating the latter protocol (much easier to intercept websocket communications as well) and I believe I can implement it as a plugin, though right now there are still many kinks with the application I have to work out. When I do get it to a state I'm happy with I'll probably release Deezer and Spotify plugins.
