### ISSUE TITLE
Crash with Could not load file or assembly Newtonsoft.Json

### ISSUE THREAD

**Issue by Perplexer1** [svbnet/Athame#30]
I'm having a problem with crashing. Here's what I got:

Windows 7 Ultimate 64-bit fully updated
Latest installed .NET Framework 4.7
Downloaded athame-0.4.3-base-plugins.zip

When I paste a Google Play Music album URL and press "Add", the program crashes with the error:
Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0'

Attached image and txt error log.

![image2](https://user-images.githubusercontent.com/29666913/27502005-323078e0-5871-11e7-8e2b-ddb6bd1c1db7.png)
[error.txt](https://github.com/svbnet/Athame/files/1099156/error.txt)

**Comment by FatKiwi** [comment]
I can confirm same crash occurs on Windows 10 x64, just tried.

**Comment by svbnet** [comment]
Should be fixed in the next release, which will be coming very soon
