### ISSUE TITLE
please joox music plugin, not required account vip and option proxy for athame

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#33]
There is a security bug that allows you to get the m4a and mp3 links from 96kbps to 320kbps without having a vip account and please integrate a proxy option for athame so get the music

You have to use ip de hong kong
[web_get_songinfo.txt](https://github.com/svbnet/Athame/files/1106042/web_get_songinfo.txt)

Here I show you an example of the script that shows the links the music files I extracted from google chrome developer tools

The file is called web_get_songinfo only that it rename it to txt

The file has a limited time and expires so they know and do not think it is a lie what I said, if you do not believe me try to use this service using ip hong kong and check that file from google chrome developer tools

**Comment by FatKiwi** [comment]
Interesting. They also seem to have HiFi option and some "ape" files, but I don't think they're listed in the API, only their size. Thanks for the information.

**Comment by svbnet** [comment]
Will not be implementing this right now, as there is more demand for Deezer and Spotify plugins.
