### ISSUE TITLE
Not an issue, it's that would be good to have

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [svbnet/Athame#36]
Maybe it exists, but i haven't found. Athame gives names to files like "1 ...", "2 ...", ..., "10 ..." but it would be good to have an option to set the format "01 ...", "02 ...", "10 ...".

Also it would be good to have an option for cases of 2 and more volumes of albums to put every part into own subfolder (of main folder of albums) with certain format, i.e. users can write some name like "CD" then they will get folders of an album with 2 parts like < album >/< CD1 > < CD2 >, or "Disc " and then < album >/< Disc 1 > < Disc 2 >, and an option for an automatically enabling this function that if the app sees albums contain 2 and more parts and the option is enabled, the app automatically put songs of every part into needed subfolders with names from a field.

**Comment by redreadnut** [comment]
I asked about song names here - https://github.com/svbnet/Athame/issues/27

**Comment by svbnet** [comment]
Yep, first bit is doable - need to bring in a library or write new code that allows format specifiers (leading zero, etc). Second bit is a little more tricky, but either way I should be able to implement it soon.
