### ISSUE TITLE
Bug: When FLAC is not available, "error occurred while downloading" and it saves as wrong extension (m4a instead of mp3)

### ISSUE THREAD

**Issue by FatKiwi** [svbnet/Athame#38]
Album ID: 1526430

Chrome fetches MP3 320 when FLAC is not available, Athame says "error occurred while downloading" but still downloads (which is good!)

Problem: Files saved as m4a instead of mp3. Cannot be played until renamed to mp3 (as they're real MP3 files with wrong extension m4a). Weird ID3 tag also appears in files: 
`FileExtension_Invalid       : m1a mpa1 mp1 m2a mpa2 mp2 mp3`

Error log:
[Error] MainForm: MDQ exception handlerCorruptFileException: Box header specified a size of {0} bytes but only {1} bytes left in the file
   at TagLib.File.Create(IFileAbstraction abstraction, String mimetype, ReadStyle propertiesStyle)
   at Athame.DownloadAndTag.TrackTagger.Write(String path, Track track)
   at Athame.DownloadAndTag.MediaDownloadQueue.<DownloadCollectionAsync>d__29.MoveNext()

**Comment by fabriccioguzman** [comment]
That a problem that can not be solved until the creator adds mp3 support to athame, this album is not available in flac nor m4a by is the error is presented

**Comment by svbnet** [comment]
The "Box header specified a size of {0} bytes but only {1} bytes left in the file" error is because some tracks on Tidal are corrupt for some reason and can't be tagged, so it is a problem with Tidal. Tidal also presents every high and low-quality track as an AAC file (i.e. .m4a).
