### ISSUE TITLE
Napster Plugin please for athame

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#39]
Hello, it helps me to convince joe to create a napster plugin, since napster uses a Dolby Encoder Encoder and I can see the direct music links a clean m4a at 320kbps in android and do not use rtmp just use the Pocket Capture app and the App napster, if they do not help me, well At least i tried to let them know that there is a security violation in napster and there is no problem

**Comment by svbnet** [comment]
Will add this to the list of the plugins to create in the near future.

**Comment by fabriccioguzman** [comment]
Thanks, I'll wait for that plugin, I appreciate it, although it would also be nice if you added option to download videos from tidal and other webs in the future
