### ISSUE TITLE
Version to title

### ISSUE THREAD

**Issue by zakatov** [svbnet/Athame#41]
Athame 0.4.4
Windows 10

Plugin Tidal.
Does not work "Append version to title".

**Comment by svbnet** [comment]
D'oh! probably forgot to implement that in the new version!

**Comment by svbnet** [comment]
Fixed, just download https://github.com/svbnet/AthamePlugin.Tidal/releases/tag/2.1 and extract it into the plugins directory, replacing the "Tidal" folder
