### ISSUE TITLE
Error when adding some tidal albums to the list

### ISSUE THREAD

**Issue by fablike** [svbnet/Athame#42]
![athame](https://user-images.githubusercontent.com/1781762/27836753-1b3b7e3c-60e1-11e7-9161-f9440300f476.PNG)

This error occurs only with some albums, but not all. I wasn't able to find the main reason...
Album used to have an error : https://listen.tidal.com/album/7599004

**Comment by fabriccioguzman** [comment]
Try removing the athame folder that is located in C: \ Users \ your user \ AppData \ Roaming
And try to delete the word listen from https://listen.tidal.com/album/7599004
Example: https://tidal.com/album/7599004
Or you copy the link of each album track either from the tidal app for pc or from the web player, I recommend you from the tidal app of pc

**Comment by fabriccioguzman** [comment]
Try copying the link for each track

**Comment by FatKiwi** [comment]
Link works for me, cannot reproduce bug.

**Comment by fabriccioguzman** [comment]
copy link track only

**Comment by fablike** [comment]
@fabriccioguzman I did all of this, and nothing works (except adding each track one by one).

I tried with Athame version 0.4.3 and it worked, but not with version 0.4.4. I can provide more logs if I find the location

**Comment by fablike** [comment]
Ok it seems like #44 is a duplicate of my issue.
