### ISSUE TITLE
Slow speed

### ISSUE THREAD

**Issue by UserForTheOnlyTopic** [svbnet/Athame#43]
Have tried Athame 4.4.0 and have noticed that speed of downloading (tidal/16bit) is reduced in a few times. The problem isn't in the Internet. After it i launched 4.3.0 and downloaded tha same album (speed of the connection was same) and downloaded as fast as it should be.
I think various new calculations like percents and stuff reduce speed too.

**Comment by fabriccioguzman** [comment]
Test that your speed is correct, can be a problem of your region, try to download it with another internet service of some friend you have or neighbor,

Or if there is not that says joe regarding this problem

**Comment by svbnet** [comment]
It's due to the FLAC decryptor, which downloads a chunk then decrypts it, making it slower. Hopefully I can improve it soon.
