### ISSUE TITLE
[REQ] Spotify / Deezer

### ISSUE THREAD

**Issue by oO-u-Oo** [svbnet/Athame#48]
Hello, 

Will you add spotify and deezer to Athame?

Thanks.

**Comment by fabriccioguzman** [comment]
Hello, sorry, the same question that asked another user, if the developer is currently working to launch the plugin to deezer, spotify and napster but it will take, we have to wait

**Comment by svbnet** [comment]
^

**Comment by oO-u-Oo** [comment]
Thanks Joe for sharing your program, waiting for that longed for version, if you could add Spotify which is the best music page by its large catalog would be great as long as it is not a sound recorder, can you decrypt mp3 files from Spotify and know the direct link of the file?

Greetings.

**Comment by Hemps37** [comment]
Qobuz security seems very lax compared to Spotify and the others, you can capture the download or stream to hdd using Fiddlerscript I adjusted from original.
