### ISSUE TITLE
24 bit tidal failed to download.

### ISSUE THREAD

**Issue by VikasRana** [svbnet/Athame#49]
What is your OS version? Win 10
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file. Yes
Have you ensured you are using the latest version? Yes
Can you play back the track or collection on the web? Yes

**Comment by fabriccioguzman** [comment]
Explain yourself better, what is the error, what song are you trying to download

**Comment by VikasRana** [comment]
I am trying to download Jay Z - 4:44 album. Issue is that its downloading regular FLAC 16 and not FLAC 24.

**Comment by fabriccioguzman** [comment]
Not yet available the new album of jay z in 24 bits or MASTER

**Comment by tocy777** [comment]
Yupp the master is not available only the E -> Explicit version

**Comment by svbnet** [comment]
Only albums with the "M" icon next to them are master, i.e. 24kHz
