### ISSUE TITLE
Qobuz plugin for athame

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#50]
Hello Joe, you are interested in the flac high fidelity streaming service called qobuz, there is currently a security bug that allows you to get the flac file without any loss
Just try to register on that web for 15 days of testing and when you play any song in HI-FI and you go to tools for developers in the network tab a link appears
Example (this link may have expired when you see this message): http://streaming.qobuz.com/file?uid=675241&eid=36352764&fmt=6&app_id=421125438&cid=426086&etsp=1499757491&hmac=RMcUfBWCpQrD3FFII73RC5dRHzk

The fiddler uses the urlhelper

If you can not, I'll see how to make a plugin for qobuz and I'll share them

Qobuz also offers hi-res quality in 24 bits and around 192khz

**Comment by tocy777** [comment]
Sadly it is not available in all country, but I could play this song without registering that you linked, so this would rock!

**Comment by Hemps37** [comment]
+1 for Qobuz, their security is one of the most lax I have seen actually, even their desktop app allows you to download to hdd.
You can capture the download using a fiddlerscript.

**Comment by fabriccioguzman** [comment]
There is come the thing, it is a little difficult to register for those who live outside of the available countries, but you only have to use a vpn and a credit card and paypal generator to get 15 days free trial
And after that it is not necessary to use vpn

**Comment by tocy777** [comment]
What :O I will try this NOW :D

**Comment by svbnet** [comment]
Looks interesting but I don't live in a supported country :(
