### ISSUE TITLE
Path formats

### ISSUE THREAD

**Issue by zakatov** [svbnet/Athame#51]
Plugin Tidal.
If the song has several artists, then the rule does not work.

Path formats
Album.Artist, Artist, AlbumArtistOrArtist.

https://listen.tidal.com/track/75730371
https://listen.tidal.com/track/75789980
https://listen.tidal.com/track/75790725

**Comment by fabriccioguzman** [comment]
Hello, it would be better to wait for the next update because it's not such a serious problem, it's silly
Whatever you decide, I'll let you know

**Comment by davecg619** [comment]
Hi no sé que ha pasado antes me abría el programa athame 4.3 y ahora me sale error  dice objeto no identificado no me deja iniciar sección

**Comment by fabriccioguzman** [comment]
tienes que eliminar la carpeta Athame que se encuentra en C:\Users\Fabriccio Guzman\AppData\Roaming
me avisas si te funcion
hay una nueva version 0.4.4: https://github.com/svbnet/Athame/releases
nuevo plugin para la version 0.4.4 https://github.com/svbnet/AthamePlugin.Tidal/releases

**Comment by davecg619** [comment]
Ok amigo yo t aviso
________________________________

**Comment by davecg619** [comment]
si funciono gracias

**Comment by svbnet** [comment]
Completed, just download the latest version from the Releases tab and replace {TrackNumber} with {TrackNumber:00} in settings :)
