### ISSUE TITLE
If you deletes a track in the menu, a unknown error appear

### ISSUE THREAD

**Issue by mcdnlds** [svbnet/Athame#55]
Tidal plugin. windows 7.
im trying to download only a part of a album, but when i delete part of it and try to download, a error box shows, im logged in my tidal hifi account, its okay when i download a full album.
its clearly a issue with the api (or maybe not?)

**Comment by fabriccioguzman** [comment]
This type of problem is not published here, you have to publish it here: https: //github.com/svbnet/AthamePlugin.Tidal/issues because the problem is in the plugin not in the athame app

Solution: copy the link of each track, not the album
Problem: wait for svbnet to update the tidal plugin

**Comment by mcdnlds** [comment]
ok thanks

**Comment by maelset00** [comment]
Hi,
Same with google play music.
But, with google play music, i think we can't in some case pick the link of a single song...

**Comment by svbnet** [comment]
@fabriccioguzman please stop policing my issues section. this is obviously a UI issue.

**Comment by fabriccioguzman** [comment]
Sorry, I just wanted to help, because I see you take so long to respond to problems and for time and I understand

I will not keep doing this
