### ISSUE TITLE
spotify plugin

### ISSUE THREAD

**Issue by provenzano2017** [svbnet/Athame#56]
Hello guys!
who can make a spotify plugin?
some tracks are not available on tidal and google play

**Comment by fabriccioguzman** [comment]
Hello, for you know, this topic about the plugin for spotify has already been talked about a few months ago and svbnet joe has confirmed that he is currently working with a plugin to spotify, napster and deezer to launch it in the future, just wait

**Comment by svbnet** [comment]
I am currently working on a Spotify plugin, it is just more difficult to write one and since I have limited time I mostly need to work on the core application.
