### ISSUE TITLE
error downloading some albums

### ISSUE THREAD

**Issue by ali2134** [svbnet/Athame#58]
i hope you can fix this i cant download some albums please `http://i.imgur.com/uTzIUr5.png`

**Comment by J05HI** [comment]
@ali2134 
Restarting helps :)

**Comment by ali2134** [comment]
no, this appear when is finishing the download for one track

**Comment by tocy777** [comment]
Sometimes it doesn't even pops up a dialogue like this from Google Music only the error icon is there and the track is not loaded.

**Comment by ali2134** [comment]
i can provide the album if you need, i have the same error in the last version

**Comment by ali2134** [comment]
i found another error on other album, the program download every song but give me error and show me an x on program, and of course don't save the track, i explain me better: i add the album, i click on download, star first track finish download and show me error and don't save, star second automatically, and again the same for all tracks

**Comment by ali2134** [comment]
why you closed my bug? it's fixed?

**Comment by ali2134** [comment]
@svbnet ?
