### ISSUE TITLE
I'm writing a Deezer plugin

### ISSUE THREAD

**Issue by J05HI** [svbnet/Athame#59]
@svbnet 
Only for information: I'm currently writing a Deezer plugin ;)
I'll inform you if it's ready.

**Comment by fabriccioguzman** [comment]
Hello, I would like each deezer music to download it with a cover to 1400x1400 or 1200x1200 and info like Copyrigth Info, ISRC code, genre, artist, album name, year and others as if you are buying music

**Comment by J05HI** [comment]
@fabriccioguzman 
I'll ad options for cover size and add all id3 tags

**Comment by ali2134** [comment]
@J05HI hi. you know if someone is doing a plugin for `music.amazon.com` ?

**Comment by J05HI** [comment]
@ali2134 
No, I don't think so. 
But why amazon music (it isn't very good and doesn't have much music) 
Use the deezer downloader without premium if it is really :)

**Comment by svbnet** [comment]
That's cool :) I started on one a while ago, let me know if you'd like to have a look at my code and I can send it over.

**Comment by J05HI** [comment]
@svbnet 
Yeah that would be amazing! 
I've written a Deezer downloader in node and translate it now to work as a extension for Athame. 
Now I would like to say thank you for the great idea of having an extendable downloader! More people should know this and could write extentions for many sites. Then you could focus at the main app.

**Comment by J05HI** [comment]
@fabriccioguzman 

What do you think?

![capture](https://user-images.githubusercontent.com/16399787/29749447-132a3092-8b2c-11e7-8560-51cdb823032e.PNG)

**Comment by UserForTheOnlyTopic** [comment]
@J05HI , make please the option "None" for arworks

**Comment by J05HI** [comment]
@UserForTheOnlyTopic 
Okay I will :)

**Comment by fabriccioguzman** [comment]
@J05HI 
Please put it up to 1400x1400 or 1200x1200, there's nothing wrong with it, it's as if you're buying music all information like copyrigth, album name of the year, bpm beats per minute, isrc, lyrics, artist, genre or Genre and others
Please

**Comment by J05HI** [comment]
@fabriccioguzman 
Let's see what I get

**Comment by J05HI** [comment]
@fabriccioguzman 
The biggest I can get through Deezer is 1200x1200.

@fabriccioguzman @UserForTheOnlyTopic 
Is this okay:
![capture](https://user-images.githubusercontent.com/16399787/29753237-51465086-8b6d-11e7-8b59-2aef0bcb3fe4.PNG)

**Comment by J05HI** [comment]
@fabriccioguzman 
The biggest I can get through Deezer is 1200x1200.

@fabriccioguzman @UserForTheOnlyTopic 
Is this okay:
![capture](https://user-images.githubusercontent.com/16399787/29753264-bc1f2acc-8b6d-11e7-85bb-664c7268a9c0.PNG)

**Comment by J05HI** [comment]
@fabriccioguzman 
Here an example what I can get:

`{  
   SNG_ID:'676183',
   PRODUCT_TRACK_ID:'19661741',
   UPLOAD_ID:0,
   SNG_TITLE:'In The End',
   ART_ID:'92',
   PROVIDER_ID:'3',
   ART_NAME:'Linkin Park',
   ARTISTS:[  
      {  
         ART_ID:'92',
         ROLE_ID:'0',
         ARTISTS_SONGS_ORDER:'1',
         ART_NAME:'Linkin Park',
         ART_PICTURE:'adf3579be3f27e52bc1520e6c462037f',
         SMARTRADIO:'1',
         RANK:'823591',
         __TYPE__:'artist'
      }
   ],
   ALB_ID:'81763',
   ALB_TITLE:'Hybrid Theory',
   TYPE:0,
   MD5_ORIGIN:'22dcdf782a84cce4fd93ab7cf7fc703c',
   VIDEO:false,
   DURATION:'216',
   ALB_PICTURE:'033a271b5ec10842c287827c39244fb5',
   ART_PICTURE:'adf3579be3f27e52bc1520e6c462037f',
   RANK_SNG:'987458',
   SMARTRADIO:'1',
   FILESIZE_AAC_64:0,
   FILESIZE_MP3_64:'1735992',
   FILESIZE_MP3_128:'3471986',
   FILESIZE_MP3_256:0,
   FILESIZE_MP3_320:'8679966',
   FILESIZE_FLAC:'25559127',
   FILESIZE:'3471986',
   GAIN:'-9.1',
   MEDIA_VERSION:'4',
   DISK_NUMBER:'1',
   TRACK_NUMBER:'8',
   VERSION:'',
   EXPLICIT_LYRICS:'0',
   RIGHTS:{  
      STREAM_ADS_AVAILABLE:true,
      STREAM_ADS:'2000-01-01',
      STREAM_SUB_AVAILABLE:true,
      STREAM_SUB:'2000-01-01'
   },
   ISRC:'USWB10002407',
   HIERARCHICAL_TITLE:'',
   SNG_CONTRIBUTORS:{  
      mainartist:[  
         'Linkin Park'
      ],
      mixer:[  
         'Andy Wallace'
      ],
      'background vocals':[  
         'Brad Delson',
         'Joseph Hahn',
         'Rob Bourdon'
      ],
      bass:[  
         'Brad Delson'
      ],
      guitar:[  
         'Brad Delson'
      ],
      masterer:[  
         'Brian "Big Bass" Gardner'
      ],
      'lead vocals':[  
         'Chester Bennington'
      ],
      producer:[  
         'Don Gilmore'
      ],
      'recording engineer':[  
         'Don Gilmore'
      ],
      'executive producer':[  
         'Jeff Blue'
      ],
      'additional engineer':[  
         'John Ewing Jr.'
      ],
      'pro tools':[  
         'John Ewing Jr.',
         'Mike Shinoda'
      ],
      dj:[  
         'Joseph Hahn'
      ],
      samples:[  
         'Joseph Hahn'
      ],
      'assistant engineer':[  
         'Matt Griffin'
      ],
      'additional vocals':[  
         'Mike Shinoda'
      ],
      beats:[  
         'Mike Shinoda'
      ],
      'main mc':[  
         'Mike Shinoda'
      ],
      drums:[  
         'Rob Bourdon'
      ],
      'mixing engineer':[  
         'Steve Sisco'
      ],
      composer:[  
         'Bennington',
         'Bourdon',
         'Delson',
         'Hahn',
         'Shinoda'
      ]
   },
   LYRICS_ID:1729846,
   COPYRIGHT:'2000 Warner Bros. Records Inc. for the U.S. and WEA International Inc. for the world outside the U.S.',
   PHYSICAL_RELEASE_DATE:'2000-10-24',
   S_MOD:1,
   S_PREMIUM:1,
   DATE_START_PREMIUM:'2000-01-01',
   DATE_START:'2000-01-01',
   STATUS:1,
   USER_ID:0,
   URL_REWRITING:'linkin-park',
   SNG_STATUS:'1',
   AVAILABLE_COUNTRIES:{  
      STREAM_ADS:[  
         'AE',
         'AF',
         'AG',
         'AI',
         'AL',
         'AM',
         'AO',
         'AQ',
         'AR',
         'AT',
         'AU',
         'AZ',
         'BA',
         'BB',
         'BD',
         'BE',
         'BF',
         'BG',
         'BH',
         'BI',
         'BJ',
         'BN',
         'BO',
         'BR',
         'BT',
         'BV',
         'BW',
         'BY',
         'CC',
         'CD',
         'CF',
         'CG',
         'CH',
         'CI',
         'CK',
         'CL',
         'CM',
         'CN',
         'CO',
         'CR',
         'CV',
         'CX',
         'CY',
         'CZ',
         'DE',
         'DJ',
         'DK',
         'DM',
         'DZ',
         'EC',
         'EE',
         'EG',
         'EH',
         'ER',
         'ES',
         'ET',
         'FI',
         'FJ',
         'FK',
         'FM',
         'FR',
         'GA',
         'GB',
         'GD',
         'GE',
         'GH',
         'GM',
         'GN',
         'GQ',
         'GR',
         'GS',
         'GT',
         'GW',
         'HK',
         'HM',
         'HN',
         'HR',
         'HU',
         'ID',
         'IE',
         'IL',
         'IN',
         'IO',
         'IQ',
         'IS',
         'IT',
         'JM',
         'JO',
         'KE',
         'KG',
         'KH',
         'KI',
         'KM',
         'KN',
         'KR',
         'KW',
         'KY',
         'KZ',
         'LA',
         'LB',
         ... 99 more items
      ],
      STREAM_SUB_ONLY:[
      ]
   },
   __TYPE__:'song',
   DIGITAL_RELEASE_DATE:'2000-10-24'
}`

**Comment by fabriccioguzman** [comment]
@J05HI
If I agree that this is 1200 :), but try to have everything as if you bought the music

And remember what I asked above about the info for the music

**Comment by J05HI** [comment]
Yeah I'll give my best :)

**Comment by fabriccioguzman** [comment]
@J05HI

One question, you can make the deezer plugin can download FLAC deezer elite

**Comment by J05HI** [comment]
@fabriccioguzman 

Let's see

**Comment by ali2134** [comment]
@J05HI deezer has flac?

**Comment by provenzano2017** [comment]
@ali2134 yes, Deezer Elite (flac)

**Comment by UserForTheOnlyTopic** [comment]
@J05HI , yeah, it's OK. Thanks!
As i see JSON has enough data to define there is a FLAC for an album or no, so you can make some flag that would show an album can be downloaded as FLAC or no. I mean users can select FLAC mode, but actualy there can to not exist a FLAC version of some album and they will get either a MP3 version or error/message (depends of realization), but after users pasted a link you can hangle it and show some flag if they can't download FLAC although they selected the FLAC mode. It would be helpful. Of course you can invent another realization that can be better, it's just my suggestion.

**Comment by J05HI** [comment]
I didn't know that there is flac at deezer

**Comment by UserForTheOnlyTopic** [comment]
They added FLAC stream not much time ago, so it's yet not famous enough.

**Comment by J05HI** [comment]
Okay let's see

**Comment by J05HI** [comment]
But who needs flac? 
Noone can hear the difference to 320 kbps

**Comment by UserForTheOnlyTopic** [comment]
Many people need FLAC at least because they can make a proper RIP into 320 with a needed codec and can make V0, and other reasons.

**Comment by J05HI** [comment]
@UserForTheOnlyTopic 
Okay :)

**Comment by fabriccioguzman** [comment]
Could you do that you can have flac from deezer?👍

**Comment by J05HI** [comment]
@fabriccioguzman 

I don't know how to get flac, I always get 320 kbps

**Comment by fabriccioguzman** [comment]
Do it so that athame not only downloads flac from tidal, that is also from deezer,

Ask svbnet joe to see what he thinks and get flac from deezer, since joe talk about deezer elite

**Comment by fabriccioguzman** [comment]
Svbnet joe talked about deezer elite

**Comment by fabriccioguzman** [comment]
To get the flac is a bit difficult as it is only transmitted with the android app sleeps, an elite deezer account and a device or horn mark sonos and with the app packet capture for android scans and you get the flac while playing but it must be Encrypted

**Comment by J05HI** [comment]
Okay but I don't really understand how to get deezer elite 
I only have trial premium accounts

**Comment by fabriccioguzman** [comment]
You know that deezer elite has test trial option 30 days, if you do not get the flac, no problem, 320kbps will be

**Comment by fabriccioguzman** [comment]
You can create an option to log in using my account in person and it can also be downloaded without account since there are songs available in my account but not in your account, due to block by region in which each account is registered.

**Comment by J05HI** [comment]
Okay I'll try but I don't have a Sonos device

**Comment by Refelinux** [comment]
No loader for deezer for today needs a block for the login and password. Because if you have a link, most likely you will download the album, even if it is not for your country. Do not bother yourself about it.

**Comment by fabriccioguzman** [comment]
@Refelinux @J05HI 
Let me tell you that I am from Panama and I can not access song that are blocked in my region, such as mysteria de datphoria http://www.deezer.com/track/75518238?utm_source=deezer&utm_content=track-75518238&utm_term=831923187_1503983402&utm_medium Web

**Comment by J05HI** [comment]
Okay, I'm from Germany and can access both. 
Use a VPN if you would like to access them on the web interface. The downloader will work without :)

**Comment by fabriccioguzman** [comment]
It does not work, I used vpn and it does not work and without account either, but if it works if I use vpn of korea and registering 30 days trial free for the account to be Korean, and there is access to the music

**Comment by fabriccioguzman** [comment]
So I said that you would add an optional login option in athame, but when you close and open athame you are using your account without a login
This to access music block using my account of korea and thus to be able to download

**Comment by fabriccioguzman** [comment]
@J05HI Aa and it is said that Deezer Elite has over 35 million songs lossless flac

**Comment by redreadnut** [comment]
Deezer flac cannot be downloaded without premium like in mp3 320 case?

**Comment by J05HI** [comment]
@redreadnut 
I don't know.
I need an account to take a look at how the data is fetched.

**Comment by J05HI** [comment]
Maybe there:
http://www.deezer.com/offers/?referer=sonos

**Comment by ali2134** [comment]
i know a album wich cant be downloaded in any downloader or stream service. with vpn or region you cant download

**Comment by redreadnut** [comment]
**@ali2134**
I know lots of them, it can be explained simply - copyright owner don't want these albums to be streamed, you can only buy them.

**Comment by ali2134** [comment]
let me ask something guys this site is fake or not : `flacalbums.com`

**Comment by fabriccioguzman** [comment]
@J05HI      Look if you fail to get flac from deezer, never mind, we settle for 320kbps mp3

But do your best to get flac and let me know if you did

**Comment by J05HI** [comment]
@fabriccioguzman 
Yeah I'll look what I can do :)

**Comment by J05HI** [comment]
@ali2134 
Fake...

**Comment by fabriccioguzman** [comment]
@J05HI 
In some future you think that you can create a plugin of Qobuz music (it offers music mp3, flac hires and normal for athame

**Comment by J05HI** [comment]
@fabriccioguzman 
I can't create that much plugins. The deezer plugin isn't that easy

**Comment by fabriccioguzman** [comment]
If that does, but if you can, at least you can create a spotify plugin even though it is another one after you finish with deezer, please, the others will see how I do, I will learn C #

**Comment by J05HI** [comment]
@fabriccioguzman 
Spotify is too hard...
Maybe someone other gets the encryption

**Comment by fabriccioguzman** [comment]
Mmmmm, You know that napster and qobuz have security flaws that allow you to get the music without any encryption using fiddler or url helper or developer tools in the network tab that is the one that analyzes the web's web

Spotify will do it by someone else

**Comment by J05HI** [comment]
@fabriccioguzman 
Okay I didn't know that. 
I'll look at them, but first give me time to understand the Plugin Api and another thing you need to know is that I'm quite new in the C# world.

**Comment by fabriccioguzman** [comment]
@J05HI
Mmmm, I did not know, I'm sorry for commenting and insisting a lot, it's because I'm desperate to have more plugins for these services and I understand that you're new to C # so that it took me a long time to deezer and like everything I want perfect I'm excited that someone Create a plugin to deezer and then it is where I ask for much to take advantage of and that they are perfect, as the subject of the metadata or info of the songs and the cover that looks perfect in image quality

Let me know if you got anything I asked for.

**Comment by J05HI** [comment]
@fabriccioguzman 
Okay I'll inform you if I have news :)

**Comment by kmafitz1** [comment]
On a side note theMaster Flac 24bit on Tidal , turns out not to be true Lossless for anyone intrested

**Comment by redreadnut** [comment]
@kmafitz1
Why you think so?

**Comment by kmafitz1** [comment]
its been put on the do not upload list on torrent sites , because spectral analysis shows it not to be Genuine true 24bit lossless

**Comment by J05HI** [comment]
@svbnet 
Can you please release your code :)

**Comment by fabriccioguzman** [comment]
@kmafitz1  
That's his lie, because if the creator svbnet joe had not enabled the 24-bit option, joe must have analyzed the music spectrum before launching the update

I just did it with the spek application for Windows and it shows me the actual 24 bits and I compare it with a 16 bit of the same song and the spectrum are different

**Comment by kmafitz1** [comment]
Don't think so , alot of the 16bit lossless are Lossy mastered and still standing by the fact that most of that 24 bit are not true losless, and indeed this has nothing to do with Svbnet Great piece of software its the files that Tidal got from the Record Companies , I think most of the guys who are spectral analysis whizzes on one i use  of the Torrent sites would agree

**Comment by kmafitz1** [comment]
http://imgur.com/a/UtVZR This is from Tidal https://listen.tidal.com/track/46664712  Its supossed to be 16bit but its lossy mastered

**Comment by fabriccioguzman** [comment]
What you want to say is that tidal is the real flac, while the flac torrents most is bone lossy is not a true lossless

Live athame, long live athame :)

**Comment by J05HI** [comment]
@kmafitz1 @fabriccioguzman 
Please open a new issue in the Play Music Library Repo and discuss it there. It's off topic here.

**Comment by fabriccioguzman** [comment]
@J05HI 
Sorry, but we're not talking about google play music, we're talking about 24 bit and 16 bit tidal and torrents

**Comment by svbnet** [comment]
The encrypted FLAC files from Tidal are in "MQA" format. The Tidal plugin just does decryption and nothing more:
https://en.wikipedia.org/wiki/Master_Quality_Authenticated

As for Deezer Elite, your best bet would be getting a Sonos machine or something and analysing the packets between the machine and the Internet. It probably just uses a different API key or something.

**Comment by Refelinux** [comment]
Really want to download FLAC from deezer ! My minimal support - coincidence, but deezer-elite is now not only for sonos - https://www.deezer.com/us/devices/hifi

**Comment by DandeeTromp325234** [comment]
Please add deezer plugin please. They have music tidal does not have. Please add it as soon as possible :)

**Comment by oO-u-Oo** [comment]
@DandeeTromp325234 

Why so hurry? , there is more than one program that download of deezer, is more important spotify because do not there is a program on the net that does it.

**Comment by redreadnut** [comment]
@oO-u-Oo
Number one is Apple Music actually (if we speak about catalog), but I agree with you that Deezer can wait a bit, a good Spotify downloader would be great, cause there are no such a prog.

**Comment by Refelinux** [comment]
The man simply warned the developer that he was working at plug-in deezer. He will not to do spotify, lol !
I'm rejoice that we can get at least it!

**Comment by redreadnut** [comment]
@Refelinux
You know, something tells me that he even wouldn't do deezer plugin. For deezer the method is known already, all you need is just adapt it for athame... Spotify is another story, here you need completely discover and create method from a blank sheet. I think that only Joe can do it, he is well skilled in this branch.

**Comment by redreadnut** [comment]
@J05HI 
How is it going with plugin? Any news about the progress or it was just a false alarm and you can't do it?

**Comment by J05HI** [comment]
@redreadnut 
Sorry but it will take some time.
I'm currently really busy.

I've release my console Deezer downloader. If you like you could take a look at it [here](https://github.com/J05HI/DeezLoadr) :)

**Comment by jonaaa20** [comment]
Deezer's FLAC is now available for Windows App, there's a script that you can download FLAC from Deezer, script for Tampermonkey etc etc.

Here: https://greasyfork.org/en/scripts/32977-deezer-download

Would be nice if it gets implemented on athame...

**Comment by kmafitz1** [comment]
Did u get this to work ? I installed script but only got low quality downloads

**Comment by Hermit121** [comment]
@kmafitz1 I got it to work and can download flac (when the track supports it)! Pretty useful since some stuff is not available on Tidal.

**Comment by kmafitz1** [comment]
Got it to work now apoligies

**Comment by jonaaa20** [comment]
Just forgot to mention too, there's this script too, this enables all the premium features on the web version of deezer (deezer.com) and remove the "This song is not available on your country" bulls**t:

https://greasyfork.org/en/scripts/9634-deezer-premium-enabler

**Comment by J05HI** [comment]
@jonaaa20
That's amazing!
Will add it :)

**Comment by jonaaa20** [comment]
@J05HI would be nice if you add a "Quality Selector" as you can see on this Script Deezer Downloader, there's a lot of Quality modes, 64, 128, 256, 320kbps and FLAC 16-bit, just a suggestion :-D

**Comment by ThePlayingGoblin** [comment]
For the deezer downloader, is there a tutorial on how to edit the tagging formula of the tool.

**Comment by ThePlayingGoblin** [comment]
Also @svbnet, could you incorporate this deezer script into athame?

**Comment by jonaaa20** [comment]
@ThePlayingGoblin No, there's no tutorial to adapt this formula.

**Comment by oO-u-Oo** [comment]
@J05HI 
Your application does not work.

**Comment by J05HI** [comment]
@oO-u-Oo

What's the problem?
Please report bugs as an issue in the repo :)

**Comment by UserForTheOnlyTopic** [comment]
@jonaaa20 thank you a lot! Can you please check your email to find a place (notification) where i asked you something and answer it?

**Comment by oO-u-Oo** [comment]
@J05HI 
It does not work with any album, the application closes.

**Comment by J05HI** [comment]
@oO-u-Oo

Okay thanks, I'll check that :)

**Comment by jonaaa20** [comment]
@UserForTheOnlyTopic hmm... there's nothing on my email, can you send it again?

**Comment by J05HI** [comment]
@oO-u-Oo 

It's working for me.
Whats your OS? Windows?
Please describe your problem better.

<img width="674" alt="capture" src="https://user-images.githubusercontent.com/16399787/33125443-bc336260-cf80-11e7-8387-5be7263b0342.PNG">

**Comment by oO-u-Oo** [comment]
@J05HI 
Windows 7 64bits

Now if it works for me at least for the moment and I have not done anything, please add the tag cover in 500x500 and all the names of the artists and (Original Mix), (Edit), (Artist Remix), etc...

**Comment by J05HI** [comment]
@oO-u-Oo
Okay.
Album cover tagging will be added with the next release :)

**Comment by J05HI** [comment]
@jonaaa20
Quality selection with FLAC will be added in the next release

**Comment by J05HI** [comment]
@ThePlayingGoblin
Tags will be already added to the MP3s.
Do you mean you would like to define custom file titles?

**Comment by oO-u-Oo** [comment]
@J05HI 
This is what I meant, there are many tracks that contain more than one artist and remix, original mix, etc... and it does not put them, if your application solved this would be perfect.

Another mistake that has its application is that in some albums the tracks have the same name because the record companies do not bother to put the remixes so it would be advisable to put the id so that all the tracks can be downloaded.

**Comment by J05HI** [comment]
@oO-u-Oo
Will be added in next release ;)
Hopefully released on friday evening (in Germany)

**Comment by J05HI** [comment]
@oO-u-Oo
Can you please give me some links to tracks which don't have remix or something like that in the title

**Comment by oO-u-Oo** [comment]
@J05HI 
With remixes, more than one artist and the same title:
http://www.deezer.com/album/11563378
http://www.deezer.com/album/9099619

**Comment by oO-u-Oo** [comment]
@J05HI 
Please add these tags.

Tag "Copyright":
Downloaded with DeezLoadr

Tag "Url":
https://deezer.com

**Comment by J05HI** [comment]
@oO-u-Oo 

Okay I'll add them.
"Downloaded with DeezLoadr" as a comment because we already have the real copyright holders in it.
As URL I'll add the full deezer url to the track.

What do you mean with translating? Translating the app?

**Comment by oO-u-Oo** [comment]
@J05HI 
It makes me illusion that in copyright tag put "Downloaded with DeezLoadr" and the URL tag put only the domain that I said because some albums disappear from deezer for some reason that I do not know, if you do not want to add it in the copyright label tell me how I can customize it to my liking please and tell me also what program I need for translate you program in my language, I will be eternally grateful for it, I said Downloaded with DeezLoadr in the copyright tag because there are many albums that do not put the name of the label on the tracks.

**Comment by jonaaa20** [comment]
In my opinion, @J05HI doesn't need to priorize the translating of the APP, i'm fine with english, he must focus on features and bugs, not on translating, he can think about it, but not now.

**Comment by oO-u-Oo** [comment]
@jonaaa20 
I have not said that he does it, I want  translate it, That's why I told him to tell me what I need and how it is done.

**Comment by J05HI** [comment]
@oO-u-Oo
Yeah like @jonaaa20 said it's currently not in priority.
If you like you can create a pull request with your changes.

**Comment by oO-u-Oo** [comment]
@J05HI 
I'll wait to the graphical interface to translate it program and customize the tags to my liking, the only thing I've managed to replace the icon with the resource hacker program.

**Comment by J05HI** [comment]
@oO-u-Oo
Okay.
Here a list of tags which are supported: [https://www.npmjs.com/package/node-id3#supported-aliases](https://www.npmjs.com/package/node-id3#supported-aliases)

**Comment by oO-u-Oo** [comment]
@J05HI 
I can not understand how it is used, by the way, your "DeezLoadr.js" file for what is it?

**Comment by J05HI** [comment]
@oO-u-Oo
It's the source code of the app :)

**Comment by J05HI** [comment]
@oO-u-Oo @jonaaa20 @UserForTheOnlyTopic @ThePlayingGoblin @kmafitz1 @Hermit121 @redreadnut @Refelinux 

I've released v1.2.0 now :)
Take a look at it here: [https://github.com/J05HI/DeezLoadr/releases](https://github.com/J05HI/DeezLoadr/releases)


I close this ticket now because I don't have the time to learn and write the Athame plugin, sorry guys :(

**DO NOT COMMENT ANYTHING RELATED TO MY DeezLoadr HERE ANYMORE!
PLEASE OPEN AN ISSUE IN THE REPO [HERE](https://github.com/J05HI/DeezLoadr/issues/new)!**

**Comment by dOooOb** [comment]
@J05HI 
Send me an invitation of https://www.teknik.io please.

**Comment by dOooOb** [comment]
@J05HI
Please, update plugin of TripleFrequency.

**Comment by J05HI** [comment]
@dOooOb
Sorry but I'm not the maintainer of SMLoadr and I don't have any invites too
Ask in the Telegram community group

**Comment by dOooOb** [comment]
@J05HI I can not register, I do not have a cell phone. :(

**Comment by J05HI** [comment]
@dOooOb
Then use TextNow for example
You get a number with it :)

**Comment by dOooOb** [comment]
@J05HI 
It is impossible for me to register in telegram even with two mobile phones of textnow what have they given me, can you create me an account please?

**Comment by UserForTheOnlyTopic** [comment]
@J05HI , hello! Can you please upload on some fileshare the current working version of your app? Just i don't have an account on Telegram, and i see there is no another place where i can download the app.

**Comment by FatKiwi** [comment]
@UserForTheOnlyTopic it's called SMLoadr now, don't bother looking for dead projects. Google is your friend.
