### ISSUE TITLE
Play Music error if starting download

### ISSUE THREAD

**Issue by J05HI** [svbnet/Athame#61]
I'm getting this error if i start the download from Play Music:

![capture](https://user-images.githubusercontent.com/16399787/29728241-6db10258-89d7-11e7-9bcd-ea45a3d8d820.PNG)

**Comment by J05HI** [comment]
Restarting fixed it :)

**Comment by UserForTheOnlyTopic** [comment]
@jonaaa20 , i don't know how to contact with you, so i'm writing it here, can you please write here a working script for qobuz (for some time, after some time you can edit your comment and remove stuff)? mine doesn't work, only creates a file with a proper filename that weighs like 200-300 kb (one piece of a song i assume).
