### ISSUE TITLE
An unknown error occurred: The operation completed successfully

### ISSUE THREAD

**Issue by nyuszika7h** [svbnet/Athame#64]
What is your OS version? **Windows 10 Home x64 (Creators Update)**
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file. **Yes**
Have you ensured you are using the latest version? **Yes (0.4.4)**
Can you play back the track or collection on the web? **Yes**

When I download a single track from TIDAL (example: https://tidal.com/track/10643013), I get this error. This is weird, because it suggests nothing went wrong and the output file appears to be fine. The stack trace doesn't seem to have anything specific to TIDAL, which is why I'm reporting it here, although it doesn't happen when I download an album. (It also happens when I download both individual tracks and albums.)

![Screenshot of the error](https://user-images.githubusercontent.com/482367/29864216-4c32ba56-8d72-11e7-9eff-b6876225b275.png)

**Comment by fabriccioguzman** [comment]
@nyuszika7h  Hi, try to close everything session in athame, then close athame, delete the athame folder that is in app data roaming and open athame and log in and downloads the track
Make sure your account is HI-FI @

**Comment by arunshand** [comment]
same  bug for me

**Comment by svbnet** [comment]
Fixed. For the technically minded, see below:

According to [this](https://msdn.microsoft.com/en-us/library/windows/desktop/ms679347(v=vs.85).aspx):

> The return value specifies the window's state before the call to the FlashWindowEx function. If the window caption was drawn as active before the call, the return value is nonzero. Otherwise, the return value is zero.

So throwing an exception (like in this case) would cause more problems than it would solve.
