### ISSUE TITLE
Login Exception - Download Exception

### ISSUE THREAD

**Issue by ChewyChop** [svbnet/Athame#65]
If you've found a bug, please answer these questions:
What is your OS version? Windows 10 X64
Have you deleted your config file? Yes
Have you ensured you are using the latest version? Yes 0.4.4
Can you play back the track or collection on the web? Yes

This issue started happening after the latest Tidal update.  I went to download an album and got an exception.  So I deleted everything including Roaming App Data stuff and relaunched.  The attached is the exception I receive when trying to start anew and login to my Tidal account.
![screen shot 2017-09-06 at 9 25 30 am](https://user-images.githubusercontent.com/30127114/30123127-c5d3dc00-92e5-11e7-9968-5c3db0ea1e02.png)

**Comment by Madeintyo** [comment]
I second this

**Comment by svbnet** [comment]
Seems like Athame is having trouble establishing a HTTPS connection. Can you access https://listen.tidal.com in your browser?

**Comment by Madeintyo** [comment]
yes always
