### ISSUE TITLE
Master quality downloading at incorrect frequency cutoff

### ISSUE THREAD

**Issue by xxtensazenxx** [svbnet/Athame#67]
Windows 10 Home 64bit
Yes, I deleted the config and .json file
Using Version 0.4.4
Yes, it plays back on the web.

The issue is with downloading Master Quality tracks on Tidal. Its downloading them incorrectly (at 41khz or  48khz instead of  88.2k or 96khz) which is stated to be the quality the tracks are recorder in on MQA's website. 

I have also recorded a track via another source and have confirmed via spectrum analysis and compared the two, and have confirmed this. 

Also, I am have Master quality selected via the Plugins tab for tidal.

Thanks for your help and your work on this project. 
![download from athame](https://user-images.githubusercontent.com/30334231/31477219-bd68779c-aed8-11e7-947f-963329eaaba4.png)
![download from other source](https://user-images.githubusercontent.com/30334231/31477220-bd7632f6-aed8-11e7-880d-f9d92b2e1c6c.png)

**Comment by vuur** [comment]
Having same issue on my end.

Thanks

**Comment by fabriccioguzman** [comment]
@xxtensazenxx Sorry But you are wrong because mqa is the codec that only works only in sound devices like dac certified by mqa this codec when they are transmitted by dac ej meridian explorer 2 the one in charge of decompressing the file to 96 khz or up to 192 khz to 24 bits although the app spek or any app tells you 48 khz or 41 khz if you play that file without using dac you would be listening at 48 khz or 41 or 44 khz

**Comment by ali2134** [comment]
@xxtensazenxx you are right

**Comment by xxtensazenxx** [comment]
From the website 

"MQA Core Decoder

This unfolds the MQA file once to deliver even higher than CD-quality. It is included in some products with digital outputs such as Bluesound, Pioneer and Onkyo players, as well as streaming services such as TIDAL and media players like Audirvana.

The first unfold recovers all the direct music-related information. Output is 88.2kHz or 96kHz."

Which makes me assume Tidal is able to output the music at 88.2kHz/96kHz, no DAC needed . A DAC is only needed for the 2nd and 3rd unfold.

**Comment by svbnet** [comment]
The Tidal desktop app presumably does all of that. At the moment it's more of a foundation for people to build on, since it does need an external player/plugin to pay it correctly.

**Comment by fabriccioguzman** [comment]
@xxtensazenxx https://en.m.wikipedia.org/wiki/Master_Quality_Authenticated

**Comment by fabriccioguzman** [comment]
@xxtensazenxx https://en.m.wikipedia.org/wiki/Master_Quality_Authenticated
