### ISSUE TITLE
Can't build .exe from .sln in Visual Studio 2015?

### ISSUE THREAD

**Issue by mR12KL** [svbnet/Athame#7]
Hi,

I've done the following things
1.  File>Open>Project/Solution
2. Selected Athame.sln
3. Changed from 'Debug' to 'Release'
4. Build>Build Solution
5. I get a bunch of errors:
https://i.gyazo.com/4745139630c2d1239344cb1fe40aee3e.png
https://i.gyazo.com/b77fe283f23384cd09bbbc0242f29907.png

Can you please shed some light on this issue? Thanks!

**Comment by Miracle1980** [comment]
I have exactly the same issue. Do you know how could i fix it?
Thanks

**Comment by svbnet** [comment]
Since I am using a slightly modified version of OpenTidl I forgot to move the DLL from my checked out version to the project's directory, so it would obviously be checked in. Hopefully it'll be fixed in the next sync. If you are looking for releases I have uploaded a release on the releases page.

**Comment by mR12KL** [comment]
Thanks for the release! I am able to get it working. I know you said in the release that there are many things however the amount of bugs makes this almost unusable for me. I think I'll stick with RedSea until more releases come out.

I think I've taken for granted your hard work. I just want to make it known that I appreciate your efforts on these programs! Thanks again!
