### ISSUE TITLE
Help Building The .exe

### ISSUE THREAD

**Issue by whatsupimr** [svbnet/Athame#70]
Can someone walk me through how to install this? Thanks!

**Comment by svbnet** [comment]
The only thing you need to do beforehand is restore nuget packages, just right click "References" and select "Manage NuGet packages", then it should prompt you to restore them. Once you've built it you need to copy and paste the plugins from the "Plugins" directory of the latest release into the bin\Debug directory, and it should load them successfully.

**Comment by whatsupimr** [comment]
And these are the steps for the .sln file or for the 3 .csproj files?
