### ISSUE TITLE
Error adding playlist Athame 0.4.5

### ISSUE THREAD

**Issue by SchwanzusLongus** [svbnet/Athame#71]
Hi,
got the following issue adding different Tidal playlists in version 0.45.
Adding single tracks works well.
My OS -> Win 10 64bit
Deleted also config.
v0.4.4. works fine.

![athame](https://user-images.githubusercontent.com/32002081/31578489-9598aa74-b122-11e7-8dd0-54dd1c4a069f.jpg)

**Comment by svbnet** [comment]
Can you please post a log? 
You can find them by copying and pasting `%appdata%\Athame\Logs` into the Windows Explorer address bar, then dragging the latest one into the comments section here. There is no sensitive information in the logs.

**Comment by SchwanzusLongus** [comment]
Hi, Joe.
I wish I could. But log directory is empty.
Don't know why. PlugIns etc. are all there, but no log ...
Deleted the directory completely, but nothing works.

**Comment by lzmichael** [comment]
Hello,

I have downloaded Athame 0.4.5, but in the .ZIP file is the old .exe file v0.4.4 included, and if i click on about it also says: v0.4.4 and not 0.4.5.

But the google plugin is updated .... whats wrong ? Is maybe a wrong .ZIP File uploaded?

**Comment by jonaaa20** [comment]
Same problem here, there's no Logs on %appdata% folder.

**Comment by lzmichael** [comment]
Where do you have downloaded 0.4.5 ? When i download it here, i always get the v0.4.4 exe .... :(

**Comment by SchwanzusLongus** [comment]
Yes, I didn't notice. It's 0.4.4.exe also in my ZIP ...

**Comment by svbnet** [comment]
Sorry! Uploaded correct zip now :)
