### ISSUE TITLE
0.4.5. still don't work

### ISSUE THREAD

**Issue by SchwanzusLongus** [svbnet/Athame#74]
Hi, Joe.
Still get error, while adding playlist to 0.4.5.
But now, I have a log.
I hope it may help you.

Best regards
[log20171017.log](https://github.com/svbnet/Athame/files/1392250/log20171017.log)

**Comment by therohanchawla** [comment]
+1 I have the same issue while doing tidal playlists.
With key not found error. Can u pls explain the error.

Albums work fine.

**Comment by svbnet** [comment]
Will be fixed in next release :)

**Comment by therohanchawla** [comment]
Been a while... When r u planning that next release?
