### ISSUE TITLE
Help Me Please!

### ISSUE THREAD

**Issue by whatsupimr** [svbnet/Athame#78]
Hi svbnet, I am having a problem with the plugins on Athame. When I put the Tidal plugin (folder name 1.3) into the plugins directory in bin/Debug/Plugins, I open Athame and it comes up with an error message saying that my plugins are installed incorrectly. Any ideas? I sent this to you a few days ago and never got a response except for "restore the NuGet packages". I have done that, but to no avail. I have never used Windows Visual Studio or Github before, so that may be a factor. Thanks!

**Comment by svbnet** [comment]
The plugin path format is a parent directory with the plugin's name, then inside that the plugin DLL with the filename "AthamePlugin.<name>.dll".
