### ISSUE TITLE
Path cannot be the empty string or all whitespace

### ISSUE THREAD

**Issue by alfablac** [svbnet/Athame#8]
On the last commit, there is this exception on whatever album one selects:

> System.ArgumentException: Path cannot be the empty string or all whitespace.
>    at System.IO.Directory.CreateDirectory(String path)
>    at Athame.DownloadAndTag.TrackDownloader.<DownloadAsync>d__15.MoveNext() in C:\Users\XXXXX\Documents\Visual Studio 2015\Projects\Athame2\Athame\DownloadAndTag\TrackDownloader.cs:line 103
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Athame.UI.MainForm.<DownloadTracks>d__22.MoveNext() in C:\Users\XXXXX\Documents\Visual Studio 2015\Projects\Athame2\Athame\UI\MainForm.cs:line 271
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Athame.UI.MainForm.<DownloadQueue>d__21.MoveNext() in C:\Users\XXXX\Documents\Visual Studio 2015\Projects\Athame2\Athame\UI\MainForm.cs:line 217
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
>    at Athame.UI.MainForm.<startDownloadButton_Click>d__43.MoveNext() in C:\Users\XXXXX\Documents\Visual Studio 2015\Projects\Athame2\Athame\UI\MainForm.cs:line 548
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
>

**Comment by svbnet** [comment]
The current commit is broken and will be fixed soon. I recommend you use the release version, on the releases tab.
