### ISSUE TITLE
 Kentucky Fried Chicken

### ISSUE THREAD

**Issue by ThePlayingGoblin** [svbnet/Athame#83]
After a bit of research, appearently MQA is lossy and not lossless, but before its acquirement with MQA, it probably delivered true lossless. Does athame give you true lossless when it downloads or does it give you the stream version MQA that is just like an AAC file.

**Comment by jonaaa20** [comment]
I don't want to be rude but that's a stupid question... but, i did some research about the Athame downloads and i got this:

![2017-10-27_16-57-40](https://user-images.githubusercontent.com/19306370/32122777-f7bffb02-bb37-11e7-8208-11f7e86a414c.png)

**Comment by fabriccioguzman** [comment]
@ThePlayingGoblin Again the same question that had previously closed athame unloads the true mqa without losses

**Comment by ThePlayingGoblin** [comment]
@jonaaa20, mqa flac is lossy with slightly better quality than aac, flac is the container they use for the lossy mqa codec. Just because it's flac doesn't mean its lossless.

**Comment by fabriccioguzman** [comment]
@ThePlayingGoblin it's ok it's ok but it's with losses but please close this problem that already existed before that is this: https://github.com/svbnet/Athame/issues/67

**Comment by redreadnut** [comment]
@ThePlayingGoblin 
Write to tidal's support and ask, - WTF they are lying about MQA. putting shit instead real MQA and also ask why there are no 320 aac at once for new realeases.

**Comment by Hermit121** [comment]
@redreadnut Its normal MQA! MQA is at the moment only available inside a FLAC container. MQA itself is lossy. There is no lossy MQA and lossless MQA. Its always like delivered by Tidal. MQA always comes in either 24bit 44.1kHz files or 24bit 48kHz files. the full signal is unfolded when a MQA capable dac plays it back. 

There are two types:
Decoder 
Renderer 

Decoder do everything by them self and just need an MQA input signal.

Renderer need a software to do the first unfold (Tidal software has this built in). The then output signal from Tidal is 24bit 88.2kHz or 24bit 96kHz( the the sampling rates the first unfold produces). This signal will than feed into the MQA renderer and the second unfold will be done inside the DAC.


Please research before you make any dumb claims.

**Comment by Hermit121** [comment]
@ThePlayingGoblin Also MQA was never lossless. It was always like it is on Tidal. Its a way to compress high-res files for music streaming + a DSP applied to it. 

The use the highest resolution master they get from a study, apply there DSP to it and than compress it with there technology. Also its only lossy in the higher part of the high-res (like 40kHz and up or smth).
Also MQA isnt always made from a 96kHz source. Many are only normal 44.1kHz. Tho it can as high as the original resolution source (384kHz or even higher(2L has a lot of recordings for example)).

**Comment by redreadnut** [comment]
@Hermit121 
Yes, I know that MQA is real, but as you can see not everyone believe in that. We have 2 sides of this - TIDAL and Athame. Considering that fact, described already before, that it's not Athame distorts the FLACs. So there is only one thing remains undiscovered - TIDAL. That's why I adviced him to ask them.

**Comment by ThePlayingGoblin** [comment]
Well, so I guess I will consider MQA as a high end AAC that's better than AAC, but not as good as a real lossless flac.

**Comment by fabriccioguzman** [comment]
@ThePlayingGoblin   Please close issue
