### ISSUE TITLE
help, athame tidal plugin error when downloading some songs due to a large list artists

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#85]
[2017-11-01T23:25:26.8283773-05:00] [Error] MainForm: MDQ exception handler
PathTooLongException: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
at System.IO.Path.NewNormalizePathLimitedChecks(String path, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
at System.IO.Path.InternalGetDirectoryName(String path)
at Athame.DownloadAndTag.MediaDownloadQueue.EnsureParentDirectories(String path)
at Athame.DownloadAndTag.MediaDownloadQueue.d__32.MoveNext()

![32310146-59f927f6-bf5e-11e7-8f21-74e92bd55c65](https://user-images.githubusercontent.com/27593140/32326402-a7e7acde-bfa0-11e7-97e0-d753d1c876b3.png)

Título	Classical Music To Watch the Ocean
Artista	Samuel Barber, Philip Glass, Ludwig van Beethoven, Franz Schubert, Maurice Ravel, Camille Saint-Saëns, Johann Sebastian Bach, Erik Satie, Felix Mendelssohn, Richard Wagner, Franz Liszt, Wolfgang Amadeus Mozart, Frédéric Chopin, Luigi Cherubini
Lanzado	2017-04-04
Canciones	23
Duración	2:04:49
Título	Classical Music To Watch the Ocean
Artista	Samuel Barber, Philip Glass, Ludwig van Beethoven, Franz Schubert, Maurice Ravel, Camille Saint-Saëns, Johann Sebastian Bach, Erik Satie, Felix Mendelssohn, Richard Wagner, Franz Liszt, Wolfgang Amadeus Mozart, Frédéric Chopin, Luigi Cherubini
Lanzado	2017-04-04
Canciones	23
Duración	2:04:49

**Comment by UserForTheOnlyTopic** [comment]
Try the following: change your Path format in Settings, for example, input "111/{TrackNumber}". When you download songs, manually rename the foldername and filenames as you want.

**Comment by abdiasriver** [comment]
use this config

[Fix temporal](https://usuariodel.club/cuenta-tidal-premium-hifi-gratis/)
