### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by oO-u-Oo** [svbnet/Athame#87]
Please add the domain https://tidal.com in the "URL" tag and Downloaded with Athame in the "Copyright" tag.

**Comment by kmafitz1** [comment]
Use mp3tag if u want that , let's not advertise Athame to Tidal

**Comment by jonaaa20** [comment]
@kmafitz1 That's what i'm doing, i always use MP3Tag for everything <3

**Comment by oO-u-Oo** [comment]
It would be nice if the Athame application itself did it, I do not think it costs so much to add it, to always depend on another application is unnecessary when it can be done perfectly in Athame.

**Comment by jonaaa20** [comment]
The problem is that isn't necessary, at least in my opinion

**Comment by redreadnut** [comment]
@oO-u-Oo Just explain why this shiet is needed?

**Comment by redreadnut** [comment]
So, you can't explain. Right?

**Comment by redreadnut** [comment]
@oO-u-Oo Are you going to respond me, little piece of req? How many times should I ask?

**Comment by svbnet** [comment]
Please be civil when writing comments. This is not a place to get mad at other people - a simple thumbs down will suffice.

I am not planning on modifying the copyright text. Adding a URL tag may be possible but it's not a priority at the moment.
