### ISSUE TITLE
New Deezer Hi-fi Flac plugin for athame please

### ISSUE THREAD

**Issue by fabriccioguzman** [svbnet/Athame#88]
Deezer new service Hi fi 
Deezer plugin please :+1:

**Comment by ThePlayingGoblin** [comment]
Yeah, I would like to see that as well.

**Comment by redreadnut** [comment]
Guzman, are you on acid?

**Comment by jonaaa20** [comment]
Let me be clear here:

**At the moment, I am mostly working on the Athame core application, so I can't spend my time writing plugins for other services. However, services like Deezer and Spotify may become available in the future.**

For now there's two alternatives to download FLAC from Deezer.

[1- This script (use it with Violentmonkey/Tampermonkey/or else)](https://greasyfork.org/en/scripts/32977-deezer-download)
2- [This simple tool](https://github.com/J05HI/DeezLoadr)

**Comment by J05HI** [comment]
Second one is currently in active development
If someone likes he can help and contribute :)

**Comment by redreadnut** [comment]
@jonaaa20 I believe he knows it already.

**Comment by fabriccioguzman** [comment]
@J05HI  Sorry about this, try downloading this song with deezloadr: http://www.deezer.com/es/track/4487551# is that I have a problem that some songs download but when playing it is not complete it cuts at the end

**Comment by J05HI** [comment]
@fabriccioguzman
No problem.
I love it if you all report bugs.
Only this way we can build an amazing application :)

**Comment by TripleFrequency** [comment]
I wrote a Deezer plugin over the past couple days. It's complete, but there are a couple improvements I want to make before release. No guarantees, but expect it tomorrow night (EST).

**Comment by fabriccioguzman** [comment]
@TripleFrequency thanks :+1:

**Comment by MalexTP** [comment]
@TripleFrequency I can't waitt XD

**Comment by oO-u-Oo** [comment]
@TripleFrequency 
With flac or without?

**Comment by J05HI** [comment]
I think with
It isn't that much additional work
Only quality number 9 :)

**Comment by TripleFrequency** [comment]
And there it is: https://github.com/TripleFrequency/AthamePlugin.Deezer

Let me know of any problems.

Also, I just wanted to say thanks to @J05HI for your work on DeezLoadr. I provide credit in the readme, but your decryption algorithm was integral in creating it.

I also mention that things may not be as well-done as they could be, since I essentially learned C# to make this over the past few days.

**Comment by TripleFrequency** [comment]
Also, @oO-u-Oo, the plugin does support FLAC.

Also, there is a small bug with directly getting tracks that I am currently fixing (I realized just after release). I'll push a small patch as soon as it's fixed.

**Comment by oO-u-Oo** [comment]
@TripleFrequency 
Thanks very much !

The mp3 downloads them with temp at the end., solve it please.

**Comment by TripleFrequency** [comment]
@oO-u-Oo I fixed it just now. I've simply updated the release, so you just need to re-download the zip file and it will work.

**Comment by oO-u-Oo** [comment]
@TripleFrequency 
Now if you download without the temp at the end, thanks again, solve when an album is not available in flac that downloads them at 320kbps without having to check the box 320 in the configuration, that is,just like the tidal plugin .

**Comment by ThePlayingGoblin** [comment]
@TripleFrequency, I'm having trouble installing it. I just get an error when I paste the plugin into the plugins folder.

**Comment by TripleFrequency** [comment]
@ThePlayingGoblin Do you have any additional information? What kind of error? Just in Windows, or something related to Athame?

**Comment by ThePlayingGoblin** [comment]
@TripleFrequency, I downloaded the zip file, the plugin is a bunch of .cs files, whereas the Tidal and Google Play plugins in athame 0.4.5 are just 2 .dll files. I really don't know how to make it work for athame :/

**Comment by TripleFrequency** [comment]
I believe you downloaded the incorrect zip file, @ThePlayingGoblin . The Deezer.zip only contains the DLLs, but the release also has two other zips (.cs source files).
![image](https://user-images.githubusercontent.com/6166013/33406552-796ca7d2-d53b-11e7-942f-82c4ee42529e.png)

**Comment by TripleFrequency** [comment]
@oO-u-Oo I have created a [new release](https://github.com/TripleFrequency/AthamePlugin.Deezer/releases) If you have any examples of files which require downgrading (I can't easily find them), I would appreciate the feedback. I simply added a checkbox to the settings (enabled by default), which will fallback to a lower quality if the desired quality is not available.

**Comment by svbnet** [comment]
Great work, @TripleFrequency! I look forward to checking it out :)

**Comment by oO-u-Oo** [comment]
Thank you very much for the quick update, sorry to tell you that it is downloaded incorrectly, the tracks downloaded in mp3 / 320kbps when the album is not available in flac and box "Quality fallback when required" is checked, they have this name "Artist - Title.flac-temp"

**Comment by TripleFrequency** [comment]
Could you post an issue on the repo now instead, I don't want to clutter Joe's issues with things that are only semi-related. If you could provide the sample link when you post the issue, that would be great.

**Comment by TripleFrequency** [comment]
@oO-u-Oo I have updated the pre-release to fix the issue you described (I still don't have a test case for it, but I found the issue). If another issue arises, please post an issue in the repo.

@svbnet You can close this again if you'd like.

**Comment by oO-u-Oo** [comment]
For example, this album is not in flac.
http://www.deezer.com/es/album/961849

**Comment by TripleFrequency** [comment]
Yes, so the updated pre-release does fix this. I just downloaded the album with FLAC set, and it fell back to MP3 and created the MP3 files. If you are not seeing that result with the updated plugin, let me know. If you want to discuss it further, please create an issue in the proper repository.

**Comment by oO-u-Oo** [comment]
@TripleFrequency 
Once again thank you very much for everything and sorry for the inconvenience caused, any problem you see I will let you know in your repository.

**Comment by TripleFrequency** [comment]
No trouble, feel free to offer any suggestions or issues you have in the future.

**Comment by J05HI** [comment]
@TripleFrequency

Great work!
