### ISSUE TITLE
Is it possible to run this on Mac?

### ISSUE THREAD

**Issue by kleagon** [svbnet/Athame#89]
Would be possible to port it to macOS?
Thanks.

**Comment by fabriccioguzman** [comment]
not

**Comment by svbnet** [comment]
It can possibly run on OS X with Mono but you will need to refactor the Win32 dependencies (TaskDialog, etc) and even then the support for WinForms on Mono is still very flakey. The next step forward will be a WPF application, meaning it can only be used on Windows unless ported by someone else.
