### ISSUE TITLE
Language

### ISSUE THREAD

**Issue by oO-u-Oo** [svbnet/Athame#91]
I would like to contribute in this project, want translate your Athame program, can you tell me please what to do.

**Comment by TripleFrequency** [comment]
I would open an issue here: https://github.com/svbnet/Athame. This is the main Athame application, and my plugin wouldn't be able to support localization without support from the main app.

**Comment by svbnet** [comment]
Please contact me at joe@svbnet.co, so I can talk to you further, thanks :)

**Comment by oO-u-Oo** [comment]
I sent you an email
