### ISSUE TITLE
Problems with artists which have a "&" in it's name

### ISSUE THREAD

**Issue by SchwanzusLongus** [svbnet/Athame#92]
I have an issue, with Deezer-Plugin.
There's a problem while downloading some songs, where artist has a "&" in it's name (so it seems to me).

[log20171203.log](https://github.com/svbnet/Athame/files/1524964/log20171203.log

**Comment by TripleFrequency** [comment]
The logs you have provided to me do not relate to the situation you describe. Based on what I see, your issue should be solved if you use the newest version (1.2.7-RC3). If you could provide a link for what you are downloading, that would be helpful if the issue persists after switching to the new version.

**Comment by SchwanzusLongus** [comment]
THX TripleFrequency,
didn't recognize that a newer version was released!
Seems to work fine now...
