### ISSUE TITLE
Quality fallback

### ISSUE THREAD

**Issue by oO-u-Oo** [svbnet/Athame#94]
Please, do not allow quality fallback in the 320kbps of tidal, a lot of tracks are downloaded in 96kbps (bad quality), I recommend that you add this option in the tidal plugin, just as TripleFrequency has done in the deezer plugin.
https://i.imgur.com/yViYsSz.png

**Comment by svbnet** [comment]
That problem is due to Tidal doing it automatically. Some Tidal tracks are stored in lossy or 96k, so regardless of your quality settings it's still possible to get those versions simply because they are the only ones available.
