### ISSUE TITLE
Allow queue to be scrollable whilst downloading

### ISSUE THREAD

**Issue by rafaeldamasceno** [svbnet/Athame#95]
Title is pretty much self explanatory.

I know we have a progress bar, but we get much better visual feedback by being allowed to see the names of the tracks that are being downloaded.

**Comment by svbnet** [comment]
It should scroll to the track that's downloading and show an animated spinner next to it.

**Comment by rafaeldamasceno** [comment]
Huh, definitely not what's happening here. It's just stuck at the beginning.

**Comment by fabriccioguzman** [comment]
@svbnet What is trying to say @rafaelmasceno is that the scroll bar does not move to see the list of songs that are lower, but it is impossible during the download, all of us the problem occurs

**Comment by svbnet** [comment]
I'll see what I can do
