### ISSUE TITLE
Add M3U/extended M3U support

### ISSUE THREAD

**Issue by rafaeldamasceno** [svbnet/Athame#96]
The ability to save the playlist as a .m3u file would be greatly appreciated for someone who has their media organized by playlists.

It's actually easy, as the format for M3U is [very simple](https://en.wikipedia.org/wiki/M3U#File_format).

A simple implementation would be a simple checkbox in the settings that saves a file as `{PlaylistName}.m3u` and the track listing in `.\` relative path format (for portability).

**Comment by svbnet** [comment]
Sounds like a good idea. Should hopefully be ready by the next release.
