### ISSUE TITLE
Close prompt.

### ISSUE THREAD

**Issue by ThePlayingGoblin** [svbnet/Athame#97]
I would like athame to have a prompt message when closing athame with pending tracks loaded onto athame or with tracks currently downloading. I was entering in lots of album urls, and accidently closed it when I wanted to start downloading and ended up spending a painful half hour adding them all back that wasn't fun. If you had a prompt before closing athame, it could help prevent a silly mistake users occasionally make.

**Comment by svbnet** [comment]
Should be able to add this to the next release.

**Comment by TripleFrequency** [comment]
Perhaps you could add an option for this in the settings? I know for me, at least, that while developing, having an additional prompt would be very annoying if I am restarting Athame every couple minutes.

**Comment by svbnet** [comment]
@TripleFrequency I can just have it ask the user if they want to confirm closing, then add a checkbox that says "Don't show this again", along with a setting.

**Comment by ThePlayingGoblin** [comment]
@TripleFrequency If there are no tracks in the queue, or if all downloads are complete, then the prompt would not appear

**Comment by svbnet** [comment]
@ThePlayingGoblin Yep
