### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Donkeyman64** [svbnet/Athame#99]
[log20171211.log](https://github.com/svbnet/Athame/files/1546605/log20171211.log)
Happens with the latest songs.Works fine with the older and regional songs.If I rename the extension from mp3-temp to mp3,the audio works.However,no artwork and other info is visible.Gives an error after the download is complete
![screenshot 1](https://user-images.githubusercontent.com/34432869/33816660-5df0551e-ddef-11e7-8e82-317a1e13c056.png)

If you've found a bug, please answer these questions:
What is your OS version? Windows 10
Have you deleted your config file? Paste the path `%appdata%\Athame` into the Windows Explorer address bar then delete the `settings.json` file. Yes I did
Have you ensured you are using the latest version?Yes
Can you play back the track or collection on the web?Yes

**Comment by svbnet** [comment]
The "genre" tag seems to be null on some (or all) Google Play tracks. This should be fixed in the next release.
